// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalardb.proto

// Protobuf Java Version: 3.25.5
package com.scalar.db.rpc;

public interface GetNamespaceTableNamesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.GetNamespaceTableNamesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string table_names = 1;</code>
   * @return A list containing the tableNames.
   */
  java.util.List<java.lang.String>
      getTableNamesList();
  /**
   * <code>repeated string table_names = 1;</code>
   * @return The count of tableNames.
   */
  int getTableNamesCount();
  /**
   * <code>repeated string table_names = 1;</code>
   * @param index The index of the element to return.
   * @return The tableNames at the given index.
   */
  java.lang.String getTableNames(int index);
  /**
   * <code>repeated string table_names = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tableNames at the given index.
   */
  com.google.protobuf.ByteString
      getTableNamesBytes(int index);
}
