// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalardb.proto

// Protobuf Java Version: 3.25.5
package com.scalar.db.rpc;

public interface NamespaceExistsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.NamespaceExistsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool exists = 1;</code>
   * @return The exists.
   */
  boolean getExists();
}
