// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalardb.proto

package com.scalar.db.rpc;

public final class ScalarDbProto {
  private ScalarDbProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Value_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_Value_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Value_TextValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_Value_TextValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Value_BlobValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_Value_BlobValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Column_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_Column_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Key_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_Key_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Get_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_Get_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Ordering_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_Ordering_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Scan_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_Scan_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_ConditionalExpression_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_ConditionalExpression_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_MutateCondition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_MutateCondition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Mutation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_Mutation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_Result_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_ScanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_ScanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_ScanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_ScanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_MutateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_MutateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TableMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TableMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TableMetadata_ColumnEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TableMetadata_ColumnEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TableMetadata_ClusteringOrderEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TableMetadata_ClusteringOrderEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_CreateNamespaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_CreateNamespaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_CreateNamespaceRequest_OptionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_CreateNamespaceRequest_OptionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_DropNamespaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_DropNamespaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_CreateTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_CreateTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_CreateTableRequest_OptionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_CreateTableRequest_OptionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_DropTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_DropTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TruncateTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TruncateTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_CreateIndexRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_CreateIndexRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_CreateIndexRequest_OptionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_CreateIndexRequest_OptionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_DropIndexRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_DropIndexRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetTableMetadataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetTableMetadataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetTableMetadataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetTableMetadataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetNamespaceTableNamesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetNamespaceTableNamesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetNamespaceTableNamesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetNamespaceTableNamesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_NamespaceExistsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_NamespaceExistsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_NamespaceExistsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_NamespaceExistsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TransactionRequest_StartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TransactionRequest_StartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TransactionRequest_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TransactionRequest_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TransactionRequest_ScanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TransactionRequest_ScanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TransactionRequest_MutateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TransactionRequest_MutateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TransactionRequest_CommitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TransactionRequest_CommitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TransactionRequest_AbortRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TransactionRequest_AbortRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TransactionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TransactionResponse_StartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TransactionResponse_StartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TransactionResponse_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TransactionResponse_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TransactionResponse_ScanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TransactionResponse_ScanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TransactionResponse_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TransactionResponse_Error_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetTransactionStateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetTransactionStateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_GetTransactionStateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_GetTransactionStateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_AbortRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_AbortRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_AbortResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_AbortResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TwoPhaseCommitTransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TwoPhaseCommitTransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TwoPhaseCommitTransactionRequest_StartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TwoPhaseCommitTransactionRequest_StartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TwoPhaseCommitTransactionRequest_JoinRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TwoPhaseCommitTransactionRequest_JoinRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TwoPhaseCommitTransactionRequest_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TwoPhaseCommitTransactionRequest_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TwoPhaseCommitTransactionRequest_ScanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TwoPhaseCommitTransactionRequest_ScanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TwoPhaseCommitTransactionRequest_MutateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TwoPhaseCommitTransactionRequest_MutateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TwoPhaseCommitTransactionRequest_PrepareRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TwoPhaseCommitTransactionRequest_PrepareRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TwoPhaseCommitTransactionRequest_ValidateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TwoPhaseCommitTransactionRequest_ValidateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TwoPhaseCommitTransactionRequest_CommitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TwoPhaseCommitTransactionRequest_CommitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TwoPhaseCommitTransactionRequest_RollbackRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TwoPhaseCommitTransactionRequest_RollbackRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TwoPhaseCommitTransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TwoPhaseCommitTransactionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TwoPhaseCommitTransactionResponse_StartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TwoPhaseCommitTransactionResponse_StartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TwoPhaseCommitTransactionResponse_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TwoPhaseCommitTransactionResponse_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TwoPhaseCommitTransactionResponse_ScanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TwoPhaseCommitTransactionResponse_ScanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TwoPhaseCommitTransactionResponse_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TwoPhaseCommitTransactionResponse_Error_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_CreateCoordinatorTablesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_CreateCoordinatorTablesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_CreateCoordinatorTablesRequest_OptionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_CreateCoordinatorTablesRequest_OptionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_DropCoordinatorTablesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_DropCoordinatorTablesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_TruncateCoordinatorTablesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_TruncateCoordinatorTablesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_CoordinatorTablesExistRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_CoordinatorTablesExistRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_CoordinatorTablesExistResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_CoordinatorTablesExistResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016scalardb.proto\022\003rpc\032\033google/protobuf/e" +
      "mpty.proto\"\305\002\n\005Value\022\014\n\004name\030\001 \001(\t\022\027\n\rbo" +
      "olean_value\030\002 \001(\010H\000\022\023\n\tint_value\030\003 \001(\005H\000" +
      "\022\026\n\014bigint_value\030\004 \001(\003H\000\022\025\n\013float_value\030" +
      "\005 \001(\002H\000\022\026\n\014double_value\030\006 \001(\001H\000\022*\n\ntext_" +
      "value\030\007 \001(\0132\024.rpc.Value.TextValueH\000\022*\n\nb" +
      "lob_value\030\010 \001(\0132\024.rpc.Value.BlobValueH\000\032" +
      ")\n\tTextValue\022\022\n\005value\030\001 \001(\tH\000\210\001\001B\010\n\006_val" +
      "ue\032)\n\tBlobValue\022\022\n\005value\030\001 \001(\014H\000\210\001\001B\010\n\006_" +
      "value:\002\030\001B\007\n\005value\"\300\001\n\006Column\022\014\n\004name\030\001 " +
      "\001(\t\022\027\n\rboolean_value\030\002 \001(\010H\000\022\023\n\tint_valu" +
      "e\030\003 \001(\005H\000\022\026\n\014bigint_value\030\004 \001(\003H\000\022\025\n\013flo" +
      "at_value\030\005 \001(\002H\000\022\026\n\014double_value\030\006 \001(\001H\000" +
      "\022\024\n\ntext_value\030\007 \001(\tH\000\022\024\n\nblob_value\030\010 \001" +
      "(\014H\000B\007\n\005value\"A\n\003Key\022\035\n\005value\030\001 \003(\0132\n.rp" +
      "c.ValueB\002\030\001\022\033\n\006column\030\002 \003(\0132\013.rpc.Column" +
      "\"\245\001\n\003Get\022\021\n\tnamespace\030\001 \001(\t\022\r\n\005table\030\002 \001" +
      "(\t\022\037\n\rpartition_key\030\003 \001(\0132\010.rpc.Key\022 \n\016c" +
      "lustering_key\030\004 \001(\0132\010.rpc.Key\022%\n\013consist" +
      "ency\030\005 \001(\0162\020.rpc.Consistency\022\022\n\nprojecti" +
      "on\030\006 \003(\t\"3\n\010Ordering\022\014\n\004name\030\001 \001(\t\022\031\n\005or" +
      "der\030\002 \001(\0162\n.rpc.Order\"\262\002\n\004Scan\022\021\n\tnamesp" +
      "ace\030\001 \001(\t\022\r\n\005table\030\002 \001(\t\022\037\n\rpartition_ke" +
      "y\030\003 \001(\0132\010.rpc.Key\022%\n\013consistency\030\004 \001(\0162\020" +
      ".rpc.Consistency\022\022\n\nprojection\030\005 \003(\t\022&\n\024" +
      "start_clustering_key\030\006 \001(\0132\010.rpc.Key\022\027\n\017" +
      "start_inclusive\030\007 \001(\010\022$\n\022end_clustering_" +
      "key\030\010 \001(\0132\010.rpc.Key\022\025\n\rend_inclusive\030\t \001" +
      "(\010\022\037\n\010ordering\030\n \003(\0132\r.rpc.Ordering\022\r\n\005l" +
      "imit\030\013 \001(\005\"\370\001\n\025ConditionalExpression\022\020\n\004" +
      "name\030\001 \001(\tB\002\030\001\022\035\n\005value\030\002 \001(\0132\n.rpc.Valu" +
      "eB\002\030\001\0225\n\010operator\030\003 \001(\0162#.rpc.Conditiona" +
      "lExpression.Operator\022\033\n\006column\030\004 \001(\0132\013.r" +
      "pc.Column\"Z\n\010Operator\022\006\n\002EQ\020\000\022\006\n\002NE\020\001\022\006\n" +
      "\002GT\020\002\022\007\n\003GTE\020\003\022\006\n\002LT\020\004\022\007\n\003LTE\020\005\022\013\n\007IS_NU" +
      "LL\020\006\022\017\n\013IS_NOT_NULL\020\007\"\315\001\n\017MutateConditio" +
      "n\022\'\n\004type\030\001 \001(\0162\031.rpc.MutateCondition.Ty" +
      "pe\022.\n\nexpression\030\002 \003(\0132\032.rpc.Conditional" +
      "Expression\"a\n\004Type\022\n\n\006PUT_IF\020\000\022\021\n\rPUT_IF" +
      "_EXISTS\020\001\022\025\n\021PUT_IF_NOT_EXISTS\020\002\022\r\n\tDELE" +
      "TE_IF\020\003\022\024\n\020DELETE_IF_EXISTS\020\004\"\272\002\n\010Mutati" +
      "on\022\021\n\tnamespace\030\001 \001(\t\022\r\n\005table\030\002 \001(\t\022\037\n\r" +
      "partition_key\030\003 \001(\0132\010.rpc.Key\022 \n\016cluster" +
      "ing_key\030\004 \001(\0132\010.rpc.Key\022%\n\013consistency\030\005" +
      " \001(\0162\020.rpc.Consistency\022\'\n\tcondition\030\006 \001(" +
      "\0132\024.rpc.MutateCondition\022 \n\004type\030\007 \001(\0162\022." +
      "rpc.Mutation.Type\022\035\n\005value\030\010 \003(\0132\n.rpc.V" +
      "alueB\002\030\001\022\033\n\006column\030\t \003(\0132\013.rpc.Column\"\033\n" +
      "\004Type\022\007\n\003PUT\020\000\022\n\n\006DELETE\020\001\"D\n\006Result\022\035\n\005" +
      "value\030\001 \003(\0132\n.rpc.ValueB\002\030\001\022\033\n\006column\030\002 " +
      "\003(\0132\013.rpc.Column\"#\n\nGetRequest\022\025\n\003get\030\001 " +
      "\001(\0132\010.rpc.Get\"*\n\013GetResponse\022\033\n\006result\030\001" +
      " \001(\0132\013.rpc.Result\"P\n\013ScanRequest\022\027\n\004scan" +
      "\030\001 \001(\0132\t.rpc.Scan\022\030\n\013fetch_count\030\002 \001(\005H\000" +
      "\210\001\001B\016\n\014_fetch_count\"E\n\014ScanResponse\022\033\n\006r" +
      "esult\030\002 \003(\0132\013.rpc.Result\022\030\n\020has_more_res" +
      "ults\030\003 \001(\010\"0\n\rMutateRequest\022\037\n\010mutation\030" +
      "\001 \003(\0132\r.rpc.Mutation\"\333\002\n\rTableMetadata\022." +
      "\n\006column\030\001 \003(\0132\036.rpc.TableMetadata.Colum" +
      "nEntry\022\032\n\022partition_key_name\030\002 \003(\t\022\033\n\023cl" +
      "ustering_key_name\030\003 \003(\t\022A\n\020clustering_or" +
      "der\030\004 \003(\0132\'.rpc.TableMetadata.Clustering" +
      "OrderEntry\022\034\n\024secondary_index_name\030\005 \003(\t" +
      "\032<\n\013ColumnEntry\022\013\n\003key\030\001 \001(\t\022\034\n\005value\030\002 " +
      "\001(\0162\r.rpc.DataType:\0028\001\032B\n\024ClusteringOrde" +
      "rEntry\022\013\n\003key\030\001 \001(\t\022\031\n\005value\030\002 \001(\0162\n.rpc" +
      ".Order:\0028\001\"\255\001\n\026CreateNamespaceRequest\022\021\n" +
      "\tnamespace\030\001 \001(\t\0229\n\007options\030\002 \003(\0132(.rpc." +
      "CreateNamespaceRequest.OptionsEntry\022\025\n\ri" +
      "f_not_exists\030\003 \001(\010\032.\n\014OptionsEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"<\n\024DropNamesp" +
      "aceRequest\022\021\n\tnamespace\030\001 \001(\t\022\021\n\tif_exis" +
      "ts\030\002 \001(\010\"\340\001\n\022CreateTableRequest\022\021\n\tnames" +
      "pace\030\001 \001(\t\022\r\n\005table\030\002 \001(\t\022*\n\016table_metad" +
      "ata\030\003 \001(\0132\022.rpc.TableMetadata\0225\n\007options" +
      "\030\004 \003(\0132$.rpc.CreateTableRequest.OptionsE" +
      "ntry\022\025\n\rif_not_exists\030\005 \001(\010\032.\n\014OptionsEn" +
      "try\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"G\n\020D" +
      "ropTableRequest\022\021\n\tnamespace\030\001 \001(\t\022\r\n\005ta" +
      "ble\030\002 \001(\t\022\021\n\tif_exists\030\003 \001(\010\"8\n\024Truncate" +
      "TableRequest\022\021\n\tnamespace\030\001 \001(\t\022\r\n\005table" +
      "\030\002 \001(\t\"\311\001\n\022CreateIndexRequest\022\021\n\tnamespa" +
      "ce\030\001 \001(\t\022\r\n\005table\030\002 \001(\t\022\023\n\013column_name\030\003" +
      " \001(\t\0225\n\007options\030\004 \003(\0132$.rpc.CreateIndexR" +
      "equest.OptionsEntry\022\025\n\rif_not_exists\030\005 \001" +
      "(\010\032.\n\014OptionsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\t:\0028\001\"\\\n\020DropIndexRequest\022\021\n\tnamesp" +
      "ace\030\001 \001(\t\022\r\n\005table\030\002 \001(\t\022\023\n\013column_name\030" +
      "\003 \001(\t\022\021\n\tif_exists\030\004 \001(\010\";\n\027GetTableMeta" +
      "dataRequest\022\021\n\tnamespace\030\001 \001(\t\022\r\n\005table\030" +
      "\002 \001(\t\"F\n\030GetTableMetadataResponse\022*\n\016tab" +
      "le_metadata\030\001 \001(\0132\022.rpc.TableMetadata\"2\n" +
      "\035GetNamespaceTableNamesRequest\022\021\n\tnamesp" +
      "ace\030\001 \001(\t\"4\n\036GetNamespaceTableNamesRespo" +
      "nse\022\022\n\ntable_name\030\001 \003(\t\"+\n\026NamespaceExis" +
      "tsRequest\022\021\n\tnamespace\030\001 \001(\t\")\n\027Namespac" +
      "eExistsResponse\022\016\n\006exists\030\001 \001(\010\"\367\004\n\022Tran" +
      "sactionRequest\022=\n\rstart_request\030\001 \001(\0132$." +
      "rpc.TransactionRequest.StartRequestH\000\0229\n" +
      "\013get_request\030\002 \001(\0132\".rpc.TransactionRequ" +
      "est.GetRequestH\000\022;\n\014scan_request\030\003 \001(\0132#" +
      ".rpc.TransactionRequest.ScanRequestH\000\022?\n" +
      "\016mutate_request\030\004 \001(\0132%.rpc.TransactionR" +
      "equest.MutateRequestH\000\022?\n\016commit_request" +
      "\030\005 \001(\0132%.rpc.TransactionRequest.CommitRe" +
      "questH\000\022=\n\rabort_request\030\006 \001(\0132$.rpc.Tra" +
      "nsactionRequest.AbortRequestH\000\032>\n\014StartR" +
      "equest\022\033\n\016transaction_id\030\001 \001(\tH\000\210\001\001B\021\n\017_" +
      "transaction_id\032#\n\nGetRequest\022\025\n\003get\030\002 \001(" +
      "\0132\010.rpc.Get\032&\n\013ScanRequest\022\027\n\004scan\030\002 \001(\013" +
      "2\t.rpc.Scan\0320\n\rMutateRequest\022\037\n\010mutation" +
      "\030\002 \003(\0132\r.rpc.Mutation\032\017\n\rCommitRequest\032\016" +
      "\n\014AbortRequestB\t\n\007request\"\311\004\n\023Transactio" +
      "nResponse\022@\n\016start_response\030\001 \001(\0132&.rpc." +
      "TransactionResponse.StartResponseH\000\022<\n\014g" +
      "et_response\030\002 \001(\0132$.rpc.TransactionRespo" +
      "nse.GetResponseH\000\022>\n\rscan_response\030\003 \001(\013" +
      "2%.rpc.TransactionResponse.ScanResponseH" +
      "\000\022/\n\005error\030\004 \001(\0132\036.rpc.TransactionRespon" +
      "se.ErrorH\000\032\'\n\rStartResponse\022\026\n\016transacti" +
      "on_id\030\001 \001(\t\032*\n\013GetResponse\022\033\n\006result\030\001 \001" +
      "(\0132\013.rpc.Result\032+\n\014ScanResponse\022\033\n\006resul" +
      "t\030\001 \003(\0132\013.rpc.Result\032\262\001\n\005Error\022<\n\nerror_" +
      "code\030\001 \001(\0162(.rpc.TransactionResponse.Err" +
      "or.ErrorCode\022\017\n\007message\030\002 \001(\t\"Z\n\tErrorCo" +
      "de\022\024\n\020INVALID_ARGUMENT\020\000\022\014\n\010CONFLICT\020\001\022\036" +
      "\n\032UNKNOWN_TRANSACTION_STATUS\020\002\022\t\n\005OTHER\020" +
      "\003B\n\n\010response\"4\n\032GetTransactionStateRequ" +
      "est\022\026\n\016transaction_id\030\001 \001(\t\"C\n\033GetTransa" +
      "ctionStateResponse\022$\n\005state\030\001 \001(\0162\025.rpc." +
      "TransactionState\"&\n\014AbortRequest\022\026\n\016tran" +
      "saction_id\030\001 \001(\t\"5\n\rAbortResponse\022$\n\005sta" +
      "te\030\001 \001(\0162\025.rpc.TransactionState\"\235\010\n TwoP" +
      "haseCommitTransactionRequest\022K\n\rstart_re" +
      "quest\030\001 \001(\01322.rpc.TwoPhaseCommitTransact" +
      "ionRequest.StartRequestH\000\022I\n\014join_reques" +
      "t\030\002 \001(\01321.rpc.TwoPhaseCommitTransactionR" +
      "equest.JoinRequestH\000\022G\n\013get_request\030\003 \001(" +
      "\01320.rpc.TwoPhaseCommitTransactionRequest" +
      ".GetRequestH\000\022I\n\014scan_request\030\004 \001(\01321.rp" +
      "c.TwoPhaseCommitTransactionRequest.ScanR" +
      "equestH\000\022M\n\016mutate_request\030\005 \001(\01323.rpc.T" +
      "woPhaseCommitTransactionRequest.MutateRe" +
      "questH\000\022O\n\017prepare_request\030\006 \001(\01324.rpc.T" +
      "woPhaseCommitTransactionRequest.PrepareR" +
      "equestH\000\022Q\n\020validate_request\030\007 \001(\01325.rpc" +
      ".TwoPhaseCommitTransactionRequest.Valida" +
      "teRequestH\000\022M\n\016commit_request\030\010 \001(\01323.rp" +
      "c.TwoPhaseCommitTransactionRequest.Commi" +
      "tRequestH\000\022Q\n\020rollback_request\030\t \001(\01325.r" +
      "pc.TwoPhaseCommitTransactionRequest.Roll" +
      "backRequestH\000\032>\n\014StartRequest\022\033\n\016transac" +
      "tion_id\030\001 \001(\tH\000\210\001\001B\021\n\017_transaction_id\032%\n" +
      "\013JoinRequest\022\026\n\016transaction_id\030\001 \001(\t\032#\n\n" +
      "GetRequest\022\025\n\003get\030\002 \001(\0132\010.rpc.Get\032&\n\013Sca" +
      "nRequest\022\027\n\004scan\030\002 \001(\0132\t.rpc.Scan\0320\n\rMut" +
      "ateRequest\022\037\n\010mutation\030\002 \003(\0132\r.rpc.Mutat" +
      "ion\032\020\n\016PrepareRequest\032\021\n\017ValidateRequest" +
      "\032\017\n\rCommitRequest\032\021\n\017RollbackRequestB\t\n\007" +
      "request\"\226\005\n!TwoPhaseCommitTransactionRes" +
      "ponse\022N\n\016start_response\030\001 \001(\01324.rpc.TwoP" +
      "haseCommitTransactionResponse.StartRespo" +
      "nseH\000\022J\n\014get_response\030\002 \001(\01322.rpc.TwoPha" +
      "seCommitTransactionResponse.GetResponseH" +
      "\000\022L\n\rscan_response\030\003 \001(\01323.rpc.TwoPhaseC" +
      "ommitTransactionResponse.ScanResponseH\000\022" +
      "=\n\005error\030\004 \001(\0132,.rpc.TwoPhaseCommitTrans" +
      "actionResponse.ErrorH\000\032\'\n\rStartResponse\022" +
      "\026\n\016transaction_id\030\001 \001(\t\032*\n\013GetResponse\022\033" +
      "\n\006result\030\001 \001(\0132\013.rpc.Result\032+\n\014ScanRespo" +
      "nse\022\033\n\006result\030\001 \003(\0132\013.rpc.Result\032\271\001\n\005Err" +
      "or\022J\n\nerror_code\030\001 \001(\01626.rpc.TwoPhaseCom" +
      "mitTransactionResponse.Error.ErrorCode\022\017" +
      "\n\007message\030\002 \001(\t\"S\n\tErrorCode\022\024\n\020INVALID_" +
      "ARGUMENT\020\000\022\014\n\010CONFLICT\020\001\022\027\n\023UNKNOWN_TRAN" +
      "SACTION\020\002\022\t\n\005OTHER\020\003B\n\n\010response\"\251\001\n\036Cre" +
      "ateCoordinatorTablesRequest\022A\n\007options\030\001" +
      " \003(\01320.rpc.CreateCoordinatorTablesReques" +
      "t.OptionsEntry\022\024\n\014if_not_exist\030\002 \001(\010\032.\n\014" +
      "OptionsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001\"0\n\034DropCoordinatorTablesRequest\022\020\n\010" +
      "if_exist\030\001 \001(\010\"\"\n TruncateCoordinatorTab" +
      "lesRequest\"\037\n\035CoordinatorTablesExistRequ" +
      "est\"/\n\036CoordinatorTablesExistResponse\022\r\n" +
      "\005exist\030\001 \001(\010*a\n\013Consistency\022\032\n\026CONSISTEN" +
      "CY_SEQUENTIAL\020\000\022\030\n\024CONSISTENCY_EVENTUAL\020" +
      "\001\022\034\n\030CONSISTENCY_LINEARIZABLE\020\002*&\n\005Order" +
      "\022\r\n\tORDER_ASC\020\000\022\016\n\nORDER_DESC\020\001*\235\001\n\010Data" +
      "Type\022\025\n\021DATA_TYPE_BOOLEAN\020\000\022\021\n\rDATA_TYPE" +
      "_INT\020\001\022\024\n\020DATA_TYPE_BIGINT\020\002\022\023\n\017DATA_TYP" +
      "E_FLOAT\020\003\022\024\n\020DATA_TYPE_DOUBLE\020\004\022\022\n\016DATA_" +
      "TYPE_TEXT\020\005\022\022\n\016DATA_TYPE_BLOB\020\006*q\n\020Trans" +
      "actionState\022\037\n\033TRANSACTION_STATE_COMMITT" +
      "ED\020\000\022\035\n\031TRANSACTION_STATE_ABORTED\020\001\022\035\n\031T" +
      "RANSACTION_STATE_UNKNOWN\020\0022\253\001\n\022Distribut" +
      "edStorage\022*\n\003Get\022\017.rpc.GetRequest\032\020.rpc." +
      "GetResponse\"\000\0221\n\004Scan\022\020.rpc.ScanRequest\032" +
      "\021.rpc.ScanResponse\"\000(\0010\001\0226\n\006Mutate\022\022.rpc" +
      ".MutateRequest\032\026.google.protobuf.Empty\"\000" +
      "2\367\005\n\027DistributedStorageAdmin\022H\n\017CreateNa" +
      "mespace\022\033.rpc.CreateNamespaceRequest\032\026.g" +
      "oogle.protobuf.Empty\"\000\022D\n\rDropNamespace\022" +
      "\031.rpc.DropNamespaceRequest\032\026.google.prot" +
      "obuf.Empty\"\000\022@\n\013CreateTable\022\027.rpc.Create" +
      "TableRequest\032\026.google.protobuf.Empty\"\000\022<" +
      "\n\tDropTable\022\025.rpc.DropTableRequest\032\026.goo" +
      "gle.protobuf.Empty\"\000\022D\n\rTruncateTable\022\031." +
      "rpc.TruncateTableRequest\032\026.google.protob" +
      "uf.Empty\"\000\022@\n\013CreateIndex\022\027.rpc.CreateIn" +
      "dexRequest\032\026.google.protobuf.Empty\"\000\022<\n\t" +
      "DropIndex\022\025.rpc.DropIndexRequest\032\026.googl" +
      "e.protobuf.Empty\"\000\022Q\n\020GetTableMetadata\022\034" +
      ".rpc.GetTableMetadataRequest\032\035.rpc.GetTa" +
      "bleMetadataResponse\"\000\022c\n\026GetNamespaceTab" +
      "leNames\022\".rpc.GetNamespaceTableNamesRequ" +
      "est\032#.rpc.GetNamespaceTableNamesResponse" +
      "\"\000\022N\n\017NamespaceExists\022\033.rpc.NamespaceExi" +
      "stsRequest\032\034.rpc.NamespaceExistsResponse" +
      "\"\0002\343\001\n\026DistributedTransaction\022F\n\013Transac" +
      "tion\022\027.rpc.TransactionRequest\032\030.rpc.Tran" +
      "sactionResponse\"\000(\0010\001\022O\n\010GetState\022\037.rpc." +
      "GetTransactionStateRequest\032 .rpc.GetTran" +
      "sactionStateResponse\"\000\0220\n\005Abort\022\021.rpc.Ab" +
      "ortRequest\032\022.rpc.AbortResponse\"\0002\220\002\n\031Two" +
      "PhaseCommitTransaction\022p\n\031TwoPhaseCommit" +
      "Transaction\022%.rpc.TwoPhaseCommitTransact" +
      "ionRequest\032&.rpc.TwoPhaseCommitTransacti" +
      "onResponse\"\000(\0010\001\022O\n\010GetState\022\037.rpc.GetTr" +
      "ansactionStateRequest\032 .rpc.GetTransacti" +
      "onStateResponse\"\000\0220\n\005Abort\022\021.rpc.AbortRe" +
      "quest\032\022.rpc.AbortResponse\"\0002\356\010\n\033Distribu" +
      "tedTransactionAdmin\022H\n\017CreateNamespace\022\033" +
      ".rpc.CreateNamespaceRequest\032\026.google.pro" +
      "tobuf.Empty\"\000\022D\n\rDropNamespace\022\031.rpc.Dro" +
      "pNamespaceRequest\032\026.google.protobuf.Empt" +
      "y\"\000\022@\n\013CreateTable\022\027.rpc.CreateTableRequ" +
      "est\032\026.google.protobuf.Empty\"\000\022<\n\tDropTab" +
      "le\022\025.rpc.DropTableRequest\032\026.google.proto" +
      "buf.Empty\"\000\022D\n\rTruncateTable\022\031.rpc.Trunc" +
      "ateTableRequest\032\026.google.protobuf.Empty\"" +
      "\000\022@\n\013CreateIndex\022\027.rpc.CreateIndexReques" +
      "t\032\026.google.protobuf.Empty\"\000\022<\n\tDropIndex" +
      "\022\025.rpc.DropIndexRequest\032\026.google.protobu" +
      "f.Empty\"\000\022Q\n\020GetTableMetadata\022\034.rpc.GetT" +
      "ableMetadataRequest\032\035.rpc.GetTableMetada" +
      "taResponse\"\000\022c\n\026GetNamespaceTableNames\022\"" +
      ".rpc.GetNamespaceTableNamesRequest\032#.rpc" +
      ".GetNamespaceTableNamesResponse\"\000\022N\n\017Nam" +
      "espaceExists\022\033.rpc.NamespaceExistsReques" +
      "t\032\034.rpc.NamespaceExistsResponse\"\000\022X\n\027Cre" +
      "ateCoordinatorTables\022#.rpc.CreateCoordin" +
      "atorTablesRequest\032\026.google.protobuf.Empt" +
      "y\"\000\022T\n\025DropCoordinatorTables\022!.rpc.DropC" +
      "oordinatorTablesRequest\032\026.google.protobu" +
      "f.Empty\"\000\022\\\n\031TruncateCoordinatorTables\022%" +
      ".rpc.TruncateCoordinatorTablesRequest\032\026." +
      "google.protobuf.Empty\"\000\022c\n\026CoordinatorTa" +
      "blesExist\022\".rpc.CoordinatorTablesExistRe" +
      "quest\032#.rpc.CoordinatorTablesExistRespon" +
      "se\"\000B$\n\021com.scalar.db.rpcB\rScalarDbProto" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_rpc_Value_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpc_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_Value_descriptor,
        new java.lang.String[] { "Name", "BooleanValue", "IntValue", "BigintValue", "FloatValue", "DoubleValue", "TextValue", "BlobValue", "Value", });
    internal_static_rpc_Value_TextValue_descriptor =
      internal_static_rpc_Value_descriptor.getNestedTypes().get(0);
    internal_static_rpc_Value_TextValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_Value_TextValue_descriptor,
        new java.lang.String[] { "Value", "Value", });
    internal_static_rpc_Value_BlobValue_descriptor =
      internal_static_rpc_Value_descriptor.getNestedTypes().get(1);
    internal_static_rpc_Value_BlobValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_Value_BlobValue_descriptor,
        new java.lang.String[] { "Value", "Value", });
    internal_static_rpc_Column_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rpc_Column_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_Column_descriptor,
        new java.lang.String[] { "Name", "BooleanValue", "IntValue", "BigintValue", "FloatValue", "DoubleValue", "TextValue", "BlobValue", "Value", });
    internal_static_rpc_Key_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_rpc_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_Key_descriptor,
        new java.lang.String[] { "Value", "Column", });
    internal_static_rpc_Get_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_rpc_Get_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_Get_descriptor,
        new java.lang.String[] { "Namespace", "Table", "PartitionKey", "ClusteringKey", "Consistency", "Projection", });
    internal_static_rpc_Ordering_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_rpc_Ordering_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_Ordering_descriptor,
        new java.lang.String[] { "Name", "Order", });
    internal_static_rpc_Scan_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_rpc_Scan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_Scan_descriptor,
        new java.lang.String[] { "Namespace", "Table", "PartitionKey", "Consistency", "Projection", "StartClusteringKey", "StartInclusive", "EndClusteringKey", "EndInclusive", "Ordering", "Limit", });
    internal_static_rpc_ConditionalExpression_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_rpc_ConditionalExpression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_ConditionalExpression_descriptor,
        new java.lang.String[] { "Name", "Value", "Operator", "Column", });
    internal_static_rpc_MutateCondition_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_rpc_MutateCondition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_MutateCondition_descriptor,
        new java.lang.String[] { "Type", "Expression", });
    internal_static_rpc_Mutation_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_rpc_Mutation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_Mutation_descriptor,
        new java.lang.String[] { "Namespace", "Table", "PartitionKey", "ClusteringKey", "Consistency", "Condition", "Type", "Value", "Column", });
    internal_static_rpc_Result_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_rpc_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_Result_descriptor,
        new java.lang.String[] { "Value", "Column", });
    internal_static_rpc_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_rpc_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetRequest_descriptor,
        new java.lang.String[] { "Get", });
    internal_static_rpc_GetResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_rpc_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_rpc_ScanRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_rpc_ScanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_ScanRequest_descriptor,
        new java.lang.String[] { "Scan", "FetchCount", "FetchCount", });
    internal_static_rpc_ScanResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_rpc_ScanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_ScanResponse_descriptor,
        new java.lang.String[] { "Result", "HasMoreResults", });
    internal_static_rpc_MutateRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_rpc_MutateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_MutateRequest_descriptor,
        new java.lang.String[] { "Mutation", });
    internal_static_rpc_TableMetadata_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_rpc_TableMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TableMetadata_descriptor,
        new java.lang.String[] { "Column", "PartitionKeyName", "ClusteringKeyName", "ClusteringOrder", "SecondaryIndexName", });
    internal_static_rpc_TableMetadata_ColumnEntry_descriptor =
      internal_static_rpc_TableMetadata_descriptor.getNestedTypes().get(0);
    internal_static_rpc_TableMetadata_ColumnEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TableMetadata_ColumnEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rpc_TableMetadata_ClusteringOrderEntry_descriptor =
      internal_static_rpc_TableMetadata_descriptor.getNestedTypes().get(1);
    internal_static_rpc_TableMetadata_ClusteringOrderEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TableMetadata_ClusteringOrderEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rpc_CreateNamespaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_rpc_CreateNamespaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_CreateNamespaceRequest_descriptor,
        new java.lang.String[] { "Namespace", "Options", "IfNotExists", });
    internal_static_rpc_CreateNamespaceRequest_OptionsEntry_descriptor =
      internal_static_rpc_CreateNamespaceRequest_descriptor.getNestedTypes().get(0);
    internal_static_rpc_CreateNamespaceRequest_OptionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_CreateNamespaceRequest_OptionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rpc_DropNamespaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_rpc_DropNamespaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_DropNamespaceRequest_descriptor,
        new java.lang.String[] { "Namespace", "IfExists", });
    internal_static_rpc_CreateTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_rpc_CreateTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_CreateTableRequest_descriptor,
        new java.lang.String[] { "Namespace", "Table", "TableMetadata", "Options", "IfNotExists", });
    internal_static_rpc_CreateTableRequest_OptionsEntry_descriptor =
      internal_static_rpc_CreateTableRequest_descriptor.getNestedTypes().get(0);
    internal_static_rpc_CreateTableRequest_OptionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_CreateTableRequest_OptionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rpc_DropTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_rpc_DropTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_DropTableRequest_descriptor,
        new java.lang.String[] { "Namespace", "Table", "IfExists", });
    internal_static_rpc_TruncateTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_rpc_TruncateTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TruncateTableRequest_descriptor,
        new java.lang.String[] { "Namespace", "Table", });
    internal_static_rpc_CreateIndexRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_rpc_CreateIndexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_CreateIndexRequest_descriptor,
        new java.lang.String[] { "Namespace", "Table", "ColumnName", "Options", "IfNotExists", });
    internal_static_rpc_CreateIndexRequest_OptionsEntry_descriptor =
      internal_static_rpc_CreateIndexRequest_descriptor.getNestedTypes().get(0);
    internal_static_rpc_CreateIndexRequest_OptionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_CreateIndexRequest_OptionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rpc_DropIndexRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_rpc_DropIndexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_DropIndexRequest_descriptor,
        new java.lang.String[] { "Namespace", "Table", "ColumnName", "IfExists", });
    internal_static_rpc_GetTableMetadataRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_rpc_GetTableMetadataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetTableMetadataRequest_descriptor,
        new java.lang.String[] { "Namespace", "Table", });
    internal_static_rpc_GetTableMetadataResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_rpc_GetTableMetadataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetTableMetadataResponse_descriptor,
        new java.lang.String[] { "TableMetadata", });
    internal_static_rpc_GetNamespaceTableNamesRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_rpc_GetNamespaceTableNamesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetNamespaceTableNamesRequest_descriptor,
        new java.lang.String[] { "Namespace", });
    internal_static_rpc_GetNamespaceTableNamesResponse_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_rpc_GetNamespaceTableNamesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetNamespaceTableNamesResponse_descriptor,
        new java.lang.String[] { "TableName", });
    internal_static_rpc_NamespaceExistsRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_rpc_NamespaceExistsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_NamespaceExistsRequest_descriptor,
        new java.lang.String[] { "Namespace", });
    internal_static_rpc_NamespaceExistsResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_rpc_NamespaceExistsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_NamespaceExistsResponse_descriptor,
        new java.lang.String[] { "Exists", });
    internal_static_rpc_TransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_rpc_TransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TransactionRequest_descriptor,
        new java.lang.String[] { "StartRequest", "GetRequest", "ScanRequest", "MutateRequest", "CommitRequest", "AbortRequest", "Request", });
    internal_static_rpc_TransactionRequest_StartRequest_descriptor =
      internal_static_rpc_TransactionRequest_descriptor.getNestedTypes().get(0);
    internal_static_rpc_TransactionRequest_StartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TransactionRequest_StartRequest_descriptor,
        new java.lang.String[] { "TransactionId", "TransactionId", });
    internal_static_rpc_TransactionRequest_GetRequest_descriptor =
      internal_static_rpc_TransactionRequest_descriptor.getNestedTypes().get(1);
    internal_static_rpc_TransactionRequest_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TransactionRequest_GetRequest_descriptor,
        new java.lang.String[] { "Get", });
    internal_static_rpc_TransactionRequest_ScanRequest_descriptor =
      internal_static_rpc_TransactionRequest_descriptor.getNestedTypes().get(2);
    internal_static_rpc_TransactionRequest_ScanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TransactionRequest_ScanRequest_descriptor,
        new java.lang.String[] { "Scan", });
    internal_static_rpc_TransactionRequest_MutateRequest_descriptor =
      internal_static_rpc_TransactionRequest_descriptor.getNestedTypes().get(3);
    internal_static_rpc_TransactionRequest_MutateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TransactionRequest_MutateRequest_descriptor,
        new java.lang.String[] { "Mutation", });
    internal_static_rpc_TransactionRequest_CommitRequest_descriptor =
      internal_static_rpc_TransactionRequest_descriptor.getNestedTypes().get(4);
    internal_static_rpc_TransactionRequest_CommitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TransactionRequest_CommitRequest_descriptor,
        new java.lang.String[] { });
    internal_static_rpc_TransactionRequest_AbortRequest_descriptor =
      internal_static_rpc_TransactionRequest_descriptor.getNestedTypes().get(5);
    internal_static_rpc_TransactionRequest_AbortRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TransactionRequest_AbortRequest_descriptor,
        new java.lang.String[] { });
    internal_static_rpc_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_rpc_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TransactionResponse_descriptor,
        new java.lang.String[] { "StartResponse", "GetResponse", "ScanResponse", "Error", "Response", });
    internal_static_rpc_TransactionResponse_StartResponse_descriptor =
      internal_static_rpc_TransactionResponse_descriptor.getNestedTypes().get(0);
    internal_static_rpc_TransactionResponse_StartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TransactionResponse_StartResponse_descriptor,
        new java.lang.String[] { "TransactionId", });
    internal_static_rpc_TransactionResponse_GetResponse_descriptor =
      internal_static_rpc_TransactionResponse_descriptor.getNestedTypes().get(1);
    internal_static_rpc_TransactionResponse_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TransactionResponse_GetResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_rpc_TransactionResponse_ScanResponse_descriptor =
      internal_static_rpc_TransactionResponse_descriptor.getNestedTypes().get(2);
    internal_static_rpc_TransactionResponse_ScanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TransactionResponse_ScanResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_rpc_TransactionResponse_Error_descriptor =
      internal_static_rpc_TransactionResponse_descriptor.getNestedTypes().get(3);
    internal_static_rpc_TransactionResponse_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TransactionResponse_Error_descriptor,
        new java.lang.String[] { "ErrorCode", "Message", });
    internal_static_rpc_GetTransactionStateRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_rpc_GetTransactionStateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetTransactionStateRequest_descriptor,
        new java.lang.String[] { "TransactionId", });
    internal_static_rpc_GetTransactionStateResponse_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_rpc_GetTransactionStateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_GetTransactionStateResponse_descriptor,
        new java.lang.String[] { "State", });
    internal_static_rpc_AbortRequest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_rpc_AbortRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_AbortRequest_descriptor,
        new java.lang.String[] { "TransactionId", });
    internal_static_rpc_AbortResponse_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_rpc_AbortResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_AbortResponse_descriptor,
        new java.lang.String[] { "State", });
    internal_static_rpc_TwoPhaseCommitTransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_rpc_TwoPhaseCommitTransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TwoPhaseCommitTransactionRequest_descriptor,
        new java.lang.String[] { "StartRequest", "JoinRequest", "GetRequest", "ScanRequest", "MutateRequest", "PrepareRequest", "ValidateRequest", "CommitRequest", "RollbackRequest", "Request", });
    internal_static_rpc_TwoPhaseCommitTransactionRequest_StartRequest_descriptor =
      internal_static_rpc_TwoPhaseCommitTransactionRequest_descriptor.getNestedTypes().get(0);
    internal_static_rpc_TwoPhaseCommitTransactionRequest_StartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TwoPhaseCommitTransactionRequest_StartRequest_descriptor,
        new java.lang.String[] { "TransactionId", "TransactionId", });
    internal_static_rpc_TwoPhaseCommitTransactionRequest_JoinRequest_descriptor =
      internal_static_rpc_TwoPhaseCommitTransactionRequest_descriptor.getNestedTypes().get(1);
    internal_static_rpc_TwoPhaseCommitTransactionRequest_JoinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TwoPhaseCommitTransactionRequest_JoinRequest_descriptor,
        new java.lang.String[] { "TransactionId", });
    internal_static_rpc_TwoPhaseCommitTransactionRequest_GetRequest_descriptor =
      internal_static_rpc_TwoPhaseCommitTransactionRequest_descriptor.getNestedTypes().get(2);
    internal_static_rpc_TwoPhaseCommitTransactionRequest_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TwoPhaseCommitTransactionRequest_GetRequest_descriptor,
        new java.lang.String[] { "Get", });
    internal_static_rpc_TwoPhaseCommitTransactionRequest_ScanRequest_descriptor =
      internal_static_rpc_TwoPhaseCommitTransactionRequest_descriptor.getNestedTypes().get(3);
    internal_static_rpc_TwoPhaseCommitTransactionRequest_ScanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TwoPhaseCommitTransactionRequest_ScanRequest_descriptor,
        new java.lang.String[] { "Scan", });
    internal_static_rpc_TwoPhaseCommitTransactionRequest_MutateRequest_descriptor =
      internal_static_rpc_TwoPhaseCommitTransactionRequest_descriptor.getNestedTypes().get(4);
    internal_static_rpc_TwoPhaseCommitTransactionRequest_MutateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TwoPhaseCommitTransactionRequest_MutateRequest_descriptor,
        new java.lang.String[] { "Mutation", });
    internal_static_rpc_TwoPhaseCommitTransactionRequest_PrepareRequest_descriptor =
      internal_static_rpc_TwoPhaseCommitTransactionRequest_descriptor.getNestedTypes().get(5);
    internal_static_rpc_TwoPhaseCommitTransactionRequest_PrepareRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TwoPhaseCommitTransactionRequest_PrepareRequest_descriptor,
        new java.lang.String[] { });
    internal_static_rpc_TwoPhaseCommitTransactionRequest_ValidateRequest_descriptor =
      internal_static_rpc_TwoPhaseCommitTransactionRequest_descriptor.getNestedTypes().get(6);
    internal_static_rpc_TwoPhaseCommitTransactionRequest_ValidateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TwoPhaseCommitTransactionRequest_ValidateRequest_descriptor,
        new java.lang.String[] { });
    internal_static_rpc_TwoPhaseCommitTransactionRequest_CommitRequest_descriptor =
      internal_static_rpc_TwoPhaseCommitTransactionRequest_descriptor.getNestedTypes().get(7);
    internal_static_rpc_TwoPhaseCommitTransactionRequest_CommitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TwoPhaseCommitTransactionRequest_CommitRequest_descriptor,
        new java.lang.String[] { });
    internal_static_rpc_TwoPhaseCommitTransactionRequest_RollbackRequest_descriptor =
      internal_static_rpc_TwoPhaseCommitTransactionRequest_descriptor.getNestedTypes().get(8);
    internal_static_rpc_TwoPhaseCommitTransactionRequest_RollbackRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TwoPhaseCommitTransactionRequest_RollbackRequest_descriptor,
        new java.lang.String[] { });
    internal_static_rpc_TwoPhaseCommitTransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_rpc_TwoPhaseCommitTransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TwoPhaseCommitTransactionResponse_descriptor,
        new java.lang.String[] { "StartResponse", "GetResponse", "ScanResponse", "Error", "Response", });
    internal_static_rpc_TwoPhaseCommitTransactionResponse_StartResponse_descriptor =
      internal_static_rpc_TwoPhaseCommitTransactionResponse_descriptor.getNestedTypes().get(0);
    internal_static_rpc_TwoPhaseCommitTransactionResponse_StartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TwoPhaseCommitTransactionResponse_StartResponse_descriptor,
        new java.lang.String[] { "TransactionId", });
    internal_static_rpc_TwoPhaseCommitTransactionResponse_GetResponse_descriptor =
      internal_static_rpc_TwoPhaseCommitTransactionResponse_descriptor.getNestedTypes().get(1);
    internal_static_rpc_TwoPhaseCommitTransactionResponse_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TwoPhaseCommitTransactionResponse_GetResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_rpc_TwoPhaseCommitTransactionResponse_ScanResponse_descriptor =
      internal_static_rpc_TwoPhaseCommitTransactionResponse_descriptor.getNestedTypes().get(2);
    internal_static_rpc_TwoPhaseCommitTransactionResponse_ScanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TwoPhaseCommitTransactionResponse_ScanResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_rpc_TwoPhaseCommitTransactionResponse_Error_descriptor =
      internal_static_rpc_TwoPhaseCommitTransactionResponse_descriptor.getNestedTypes().get(3);
    internal_static_rpc_TwoPhaseCommitTransactionResponse_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TwoPhaseCommitTransactionResponse_Error_descriptor,
        new java.lang.String[] { "ErrorCode", "Message", });
    internal_static_rpc_CreateCoordinatorTablesRequest_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_rpc_CreateCoordinatorTablesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_CreateCoordinatorTablesRequest_descriptor,
        new java.lang.String[] { "Options", "IfNotExist", });
    internal_static_rpc_CreateCoordinatorTablesRequest_OptionsEntry_descriptor =
      internal_static_rpc_CreateCoordinatorTablesRequest_descriptor.getNestedTypes().get(0);
    internal_static_rpc_CreateCoordinatorTablesRequest_OptionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_CreateCoordinatorTablesRequest_OptionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rpc_DropCoordinatorTablesRequest_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_rpc_DropCoordinatorTablesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_DropCoordinatorTablesRequest_descriptor,
        new java.lang.String[] { "IfExist", });
    internal_static_rpc_TruncateCoordinatorTablesRequest_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_rpc_TruncateCoordinatorTablesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_TruncateCoordinatorTablesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_rpc_CoordinatorTablesExistRequest_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_rpc_CoordinatorTablesExistRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_CoordinatorTablesExistRequest_descriptor,
        new java.lang.String[] { });
    internal_static_rpc_CoordinatorTablesExistResponse_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_rpc_CoordinatorTablesExistResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_CoordinatorTablesExistResponse_descriptor,
        new java.lang.String[] { "Exist", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
