// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalardb.proto

package com.scalar.db.rpc;

/**
 * Protobuf type {@code rpc.TransactionRequest}
 */
public final class TransactionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.TransactionRequest)
    TransactionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransactionRequest.newBuilder() to construct.
  private TransactionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransactionRequest() {
    command_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TransactionRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransactionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            command_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            argumentCase_ = 2;
            argument_ = s;
            break;
          }
          case 26: {
            com.scalar.db.rpc.Get.Builder subBuilder = null;
            if (argumentCase_ == 3) {
              subBuilder = ((com.scalar.db.rpc.Get) argument_).toBuilder();
            }
            argument_ =
                input.readMessage(com.scalar.db.rpc.Get.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.scalar.db.rpc.Get) argument_);
              argument_ = subBuilder.buildPartial();
            }
            argumentCase_ = 3;
            break;
          }
          case 34: {
            com.scalar.db.rpc.Scan.Builder subBuilder = null;
            if (argumentCase_ == 4) {
              subBuilder = ((com.scalar.db.rpc.Scan) argument_).toBuilder();
            }
            argument_ =
                input.readMessage(com.scalar.db.rpc.Scan.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.scalar.db.rpc.Scan) argument_);
              argument_ = subBuilder.buildPartial();
            }
            argumentCase_ = 4;
            break;
          }
          case 42: {
            com.scalar.db.rpc.TransactionRequest.Mutations.Builder subBuilder = null;
            if (argumentCase_ == 5) {
              subBuilder = ((com.scalar.db.rpc.TransactionRequest.Mutations) argument_).toBuilder();
            }
            argument_ =
                input.readMessage(com.scalar.db.rpc.TransactionRequest.Mutations.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.scalar.db.rpc.TransactionRequest.Mutations) argument_);
              argument_ = subBuilder.buildPartial();
            }
            argumentCase_ = 5;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scalar.db.rpc.ScalarDbProto.internal_static_rpc_TransactionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scalar.db.rpc.ScalarDbProto.internal_static_rpc_TransactionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scalar.db.rpc.TransactionRequest.class, com.scalar.db.rpc.TransactionRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code rpc.TransactionRequest.Command}
   */
  public enum Command
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>START = 0;</code>
     */
    START(0),
    /**
     * <code>GET = 1;</code>
     */
    GET(1),
    /**
     * <code>SCAN = 2;</code>
     */
    SCAN(2),
    /**
     * <code>MUTATION = 3;</code>
     */
    MUTATION(3),
    /**
     * <code>COMMIT = 4;</code>
     */
    COMMIT(4),
    /**
     * <code>ABORT = 5;</code>
     */
    ABORT(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>START = 0;</code>
     */
    public static final int START_VALUE = 0;
    /**
     * <code>GET = 1;</code>
     */
    public static final int GET_VALUE = 1;
    /**
     * <code>SCAN = 2;</code>
     */
    public static final int SCAN_VALUE = 2;
    /**
     * <code>MUTATION = 3;</code>
     */
    public static final int MUTATION_VALUE = 3;
    /**
     * <code>COMMIT = 4;</code>
     */
    public static final int COMMIT_VALUE = 4;
    /**
     * <code>ABORT = 5;</code>
     */
    public static final int ABORT_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Command valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Command forNumber(int value) {
      switch (value) {
        case 0: return START;
        case 1: return GET;
        case 2: return SCAN;
        case 3: return MUTATION;
        case 4: return COMMIT;
        case 5: return ABORT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Command>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Command> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Command>() {
            public Command findValueByNumber(int number) {
              return Command.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.scalar.db.rpc.TransactionRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final Command[] VALUES = values();

    public static Command valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Command(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:rpc.TransactionRequest.Command)
  }

  public interface MutationsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rpc.TransactionRequest.Mutations)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .rpc.Mutation mutation = 1;</code>
     */
    java.util.List<com.scalar.db.rpc.Mutation> 
        getMutationList();
    /**
     * <code>repeated .rpc.Mutation mutation = 1;</code>
     */
    com.scalar.db.rpc.Mutation getMutation(int index);
    /**
     * <code>repeated .rpc.Mutation mutation = 1;</code>
     */
    int getMutationCount();
    /**
     * <code>repeated .rpc.Mutation mutation = 1;</code>
     */
    java.util.List<? extends com.scalar.db.rpc.MutationOrBuilder> 
        getMutationOrBuilderList();
    /**
     * <code>repeated .rpc.Mutation mutation = 1;</code>
     */
    com.scalar.db.rpc.MutationOrBuilder getMutationOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code rpc.TransactionRequest.Mutations}
   */
  public static final class Mutations extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rpc.TransactionRequest.Mutations)
      MutationsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Mutations.newBuilder() to construct.
    private Mutations(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Mutations() {
      mutation_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Mutations();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Mutations(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                mutation_ = new java.util.ArrayList<com.scalar.db.rpc.Mutation>();
                mutable_bitField0_ |= 0x00000001;
              }
              mutation_.add(
                  input.readMessage(com.scalar.db.rpc.Mutation.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          mutation_ = java.util.Collections.unmodifiableList(mutation_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scalar.db.rpc.ScalarDbProto.internal_static_rpc_TransactionRequest_Mutations_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scalar.db.rpc.ScalarDbProto.internal_static_rpc_TransactionRequest_Mutations_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scalar.db.rpc.TransactionRequest.Mutations.class, com.scalar.db.rpc.TransactionRequest.Mutations.Builder.class);
    }

    public static final int MUTATION_FIELD_NUMBER = 1;
    private java.util.List<com.scalar.db.rpc.Mutation> mutation_;
    /**
     * <code>repeated .rpc.Mutation mutation = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.scalar.db.rpc.Mutation> getMutationList() {
      return mutation_;
    }
    /**
     * <code>repeated .rpc.Mutation mutation = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.scalar.db.rpc.MutationOrBuilder> 
        getMutationOrBuilderList() {
      return mutation_;
    }
    /**
     * <code>repeated .rpc.Mutation mutation = 1;</code>
     */
    @java.lang.Override
    public int getMutationCount() {
      return mutation_.size();
    }
    /**
     * <code>repeated .rpc.Mutation mutation = 1;</code>
     */
    @java.lang.Override
    public com.scalar.db.rpc.Mutation getMutation(int index) {
      return mutation_.get(index);
    }
    /**
     * <code>repeated .rpc.Mutation mutation = 1;</code>
     */
    @java.lang.Override
    public com.scalar.db.rpc.MutationOrBuilder getMutationOrBuilder(
        int index) {
      return mutation_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < mutation_.size(); i++) {
        output.writeMessage(1, mutation_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < mutation_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, mutation_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.scalar.db.rpc.TransactionRequest.Mutations)) {
        return super.equals(obj);
      }
      com.scalar.db.rpc.TransactionRequest.Mutations other = (com.scalar.db.rpc.TransactionRequest.Mutations) obj;

      if (!getMutationList()
          .equals(other.getMutationList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMutationCount() > 0) {
        hash = (37 * hash) + MUTATION_FIELD_NUMBER;
        hash = (53 * hash) + getMutationList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.scalar.db.rpc.TransactionRequest.Mutations parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scalar.db.rpc.TransactionRequest.Mutations parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scalar.db.rpc.TransactionRequest.Mutations parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scalar.db.rpc.TransactionRequest.Mutations parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scalar.db.rpc.TransactionRequest.Mutations parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.scalar.db.rpc.TransactionRequest.Mutations parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.scalar.db.rpc.TransactionRequest.Mutations parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.scalar.db.rpc.TransactionRequest.Mutations parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.scalar.db.rpc.TransactionRequest.Mutations parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.scalar.db.rpc.TransactionRequest.Mutations parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.scalar.db.rpc.TransactionRequest.Mutations parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.scalar.db.rpc.TransactionRequest.Mutations parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.scalar.db.rpc.TransactionRequest.Mutations prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rpc.TransactionRequest.Mutations}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rpc.TransactionRequest.Mutations)
        com.scalar.db.rpc.TransactionRequest.MutationsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.scalar.db.rpc.ScalarDbProto.internal_static_rpc_TransactionRequest_Mutations_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.scalar.db.rpc.ScalarDbProto.internal_static_rpc_TransactionRequest_Mutations_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.scalar.db.rpc.TransactionRequest.Mutations.class, com.scalar.db.rpc.TransactionRequest.Mutations.Builder.class);
      }

      // Construct using com.scalar.db.rpc.TransactionRequest.Mutations.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMutationFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (mutationBuilder_ == null) {
          mutation_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          mutationBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.scalar.db.rpc.ScalarDbProto.internal_static_rpc_TransactionRequest_Mutations_descriptor;
      }

      @java.lang.Override
      public com.scalar.db.rpc.TransactionRequest.Mutations getDefaultInstanceForType() {
        return com.scalar.db.rpc.TransactionRequest.Mutations.getDefaultInstance();
      }

      @java.lang.Override
      public com.scalar.db.rpc.TransactionRequest.Mutations build() {
        com.scalar.db.rpc.TransactionRequest.Mutations result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.scalar.db.rpc.TransactionRequest.Mutations buildPartial() {
        com.scalar.db.rpc.TransactionRequest.Mutations result = new com.scalar.db.rpc.TransactionRequest.Mutations(this);
        int from_bitField0_ = bitField0_;
        if (mutationBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            mutation_ = java.util.Collections.unmodifiableList(mutation_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.mutation_ = mutation_;
        } else {
          result.mutation_ = mutationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.scalar.db.rpc.TransactionRequest.Mutations) {
          return mergeFrom((com.scalar.db.rpc.TransactionRequest.Mutations)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.scalar.db.rpc.TransactionRequest.Mutations other) {
        if (other == com.scalar.db.rpc.TransactionRequest.Mutations.getDefaultInstance()) return this;
        if (mutationBuilder_ == null) {
          if (!other.mutation_.isEmpty()) {
            if (mutation_.isEmpty()) {
              mutation_ = other.mutation_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMutationIsMutable();
              mutation_.addAll(other.mutation_);
            }
            onChanged();
          }
        } else {
          if (!other.mutation_.isEmpty()) {
            if (mutationBuilder_.isEmpty()) {
              mutationBuilder_.dispose();
              mutationBuilder_ = null;
              mutation_ = other.mutation_;
              bitField0_ = (bitField0_ & ~0x00000001);
              mutationBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMutationFieldBuilder() : null;
            } else {
              mutationBuilder_.addAllMessages(other.mutation_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.scalar.db.rpc.TransactionRequest.Mutations parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.scalar.db.rpc.TransactionRequest.Mutations) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.scalar.db.rpc.Mutation> mutation_ =
        java.util.Collections.emptyList();
      private void ensureMutationIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          mutation_ = new java.util.ArrayList<com.scalar.db.rpc.Mutation>(mutation_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.scalar.db.rpc.Mutation, com.scalar.db.rpc.Mutation.Builder, com.scalar.db.rpc.MutationOrBuilder> mutationBuilder_;

      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public java.util.List<com.scalar.db.rpc.Mutation> getMutationList() {
        if (mutationBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mutation_);
        } else {
          return mutationBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public int getMutationCount() {
        if (mutationBuilder_ == null) {
          return mutation_.size();
        } else {
          return mutationBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public com.scalar.db.rpc.Mutation getMutation(int index) {
        if (mutationBuilder_ == null) {
          return mutation_.get(index);
        } else {
          return mutationBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public Builder setMutation(
          int index, com.scalar.db.rpc.Mutation value) {
        if (mutationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMutationIsMutable();
          mutation_.set(index, value);
          onChanged();
        } else {
          mutationBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public Builder setMutation(
          int index, com.scalar.db.rpc.Mutation.Builder builderForValue) {
        if (mutationBuilder_ == null) {
          ensureMutationIsMutable();
          mutation_.set(index, builderForValue.build());
          onChanged();
        } else {
          mutationBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public Builder addMutation(com.scalar.db.rpc.Mutation value) {
        if (mutationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMutationIsMutable();
          mutation_.add(value);
          onChanged();
        } else {
          mutationBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public Builder addMutation(
          int index, com.scalar.db.rpc.Mutation value) {
        if (mutationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMutationIsMutable();
          mutation_.add(index, value);
          onChanged();
        } else {
          mutationBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public Builder addMutation(
          com.scalar.db.rpc.Mutation.Builder builderForValue) {
        if (mutationBuilder_ == null) {
          ensureMutationIsMutable();
          mutation_.add(builderForValue.build());
          onChanged();
        } else {
          mutationBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public Builder addMutation(
          int index, com.scalar.db.rpc.Mutation.Builder builderForValue) {
        if (mutationBuilder_ == null) {
          ensureMutationIsMutable();
          mutation_.add(index, builderForValue.build());
          onChanged();
        } else {
          mutationBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public Builder addAllMutation(
          java.lang.Iterable<? extends com.scalar.db.rpc.Mutation> values) {
        if (mutationBuilder_ == null) {
          ensureMutationIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, mutation_);
          onChanged();
        } else {
          mutationBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public Builder clearMutation() {
        if (mutationBuilder_ == null) {
          mutation_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          mutationBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public Builder removeMutation(int index) {
        if (mutationBuilder_ == null) {
          ensureMutationIsMutable();
          mutation_.remove(index);
          onChanged();
        } else {
          mutationBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public com.scalar.db.rpc.Mutation.Builder getMutationBuilder(
          int index) {
        return getMutationFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public com.scalar.db.rpc.MutationOrBuilder getMutationOrBuilder(
          int index) {
        if (mutationBuilder_ == null) {
          return mutation_.get(index);  } else {
          return mutationBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public java.util.List<? extends com.scalar.db.rpc.MutationOrBuilder> 
           getMutationOrBuilderList() {
        if (mutationBuilder_ != null) {
          return mutationBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mutation_);
        }
      }
      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public com.scalar.db.rpc.Mutation.Builder addMutationBuilder() {
        return getMutationFieldBuilder().addBuilder(
            com.scalar.db.rpc.Mutation.getDefaultInstance());
      }
      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public com.scalar.db.rpc.Mutation.Builder addMutationBuilder(
          int index) {
        return getMutationFieldBuilder().addBuilder(
            index, com.scalar.db.rpc.Mutation.getDefaultInstance());
      }
      /**
       * <code>repeated .rpc.Mutation mutation = 1;</code>
       */
      public java.util.List<com.scalar.db.rpc.Mutation.Builder> 
           getMutationBuilderList() {
        return getMutationFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.scalar.db.rpc.Mutation, com.scalar.db.rpc.Mutation.Builder, com.scalar.db.rpc.MutationOrBuilder> 
          getMutationFieldBuilder() {
        if (mutationBuilder_ == null) {
          mutationBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.scalar.db.rpc.Mutation, com.scalar.db.rpc.Mutation.Builder, com.scalar.db.rpc.MutationOrBuilder>(
                  mutation_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          mutation_ = null;
        }
        return mutationBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rpc.TransactionRequest.Mutations)
    }

    // @@protoc_insertion_point(class_scope:rpc.TransactionRequest.Mutations)
    private static final com.scalar.db.rpc.TransactionRequest.Mutations DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.scalar.db.rpc.TransactionRequest.Mutations();
    }

    public static com.scalar.db.rpc.TransactionRequest.Mutations getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Mutations>
        PARSER = new com.google.protobuf.AbstractParser<Mutations>() {
      @java.lang.Override
      public Mutations parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Mutations(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Mutations> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Mutations> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.scalar.db.rpc.TransactionRequest.Mutations getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int argumentCase_ = 0;
  private java.lang.Object argument_;
  public enum ArgumentCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    TRANSACTION_ID(2),
    GET(3),
    SCAN(4),
    MUTATIONS(5),
    ARGUMENT_NOT_SET(0);
    private final int value;
    private ArgumentCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ArgumentCase valueOf(int value) {
      return forNumber(value);
    }

    public static ArgumentCase forNumber(int value) {
      switch (value) {
        case 2: return TRANSACTION_ID;
        case 3: return GET;
        case 4: return SCAN;
        case 5: return MUTATIONS;
        case 0: return ARGUMENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ArgumentCase
  getArgumentCase() {
    return ArgumentCase.forNumber(
        argumentCase_);
  }

  public static final int COMMAND_FIELD_NUMBER = 1;
  private int command_;
  /**
   * <code>.rpc.TransactionRequest.Command command = 1;</code>
   * @return The enum numeric value on the wire for command.
   */
  @java.lang.Override public int getCommandValue() {
    return command_;
  }
  /**
   * <code>.rpc.TransactionRequest.Command command = 1;</code>
   * @return The command.
   */
  @java.lang.Override public com.scalar.db.rpc.TransactionRequest.Command getCommand() {
    @SuppressWarnings("deprecation")
    com.scalar.db.rpc.TransactionRequest.Command result = com.scalar.db.rpc.TransactionRequest.Command.valueOf(command_);
    return result == null ? com.scalar.db.rpc.TransactionRequest.Command.UNRECOGNIZED : result;
  }

  public static final int TRANSACTION_ID_FIELD_NUMBER = 2;
  /**
   * <code>string transaction_id = 2;</code>
   * @return Whether the transactionId field is set.
   */
  public boolean hasTransactionId() {
    return argumentCase_ == 2;
  }
  /**
   * <code>string transaction_id = 2;</code>
   * @return The transactionId.
   */
  public java.lang.String getTransactionId() {
    java.lang.Object ref = "";
    if (argumentCase_ == 2) {
      ref = argument_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (argumentCase_ == 2) {
        argument_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string transaction_id = 2;</code>
   * @return The bytes for transactionId.
   */
  public com.google.protobuf.ByteString
      getTransactionIdBytes() {
    java.lang.Object ref = "";
    if (argumentCase_ == 2) {
      ref = argument_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (argumentCase_ == 2) {
        argument_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GET_FIELD_NUMBER = 3;
  /**
   * <code>.rpc.Get get = 3;</code>
   * @return Whether the get field is set.
   */
  @java.lang.Override
  public boolean hasGet() {
    return argumentCase_ == 3;
  }
  /**
   * <code>.rpc.Get get = 3;</code>
   * @return The get.
   */
  @java.lang.Override
  public com.scalar.db.rpc.Get getGet() {
    if (argumentCase_ == 3) {
       return (com.scalar.db.rpc.Get) argument_;
    }
    return com.scalar.db.rpc.Get.getDefaultInstance();
  }
  /**
   * <code>.rpc.Get get = 3;</code>
   */
  @java.lang.Override
  public com.scalar.db.rpc.GetOrBuilder getGetOrBuilder() {
    if (argumentCase_ == 3) {
       return (com.scalar.db.rpc.Get) argument_;
    }
    return com.scalar.db.rpc.Get.getDefaultInstance();
  }

  public static final int SCAN_FIELD_NUMBER = 4;
  /**
   * <code>.rpc.Scan scan = 4;</code>
   * @return Whether the scan field is set.
   */
  @java.lang.Override
  public boolean hasScan() {
    return argumentCase_ == 4;
  }
  /**
   * <code>.rpc.Scan scan = 4;</code>
   * @return The scan.
   */
  @java.lang.Override
  public com.scalar.db.rpc.Scan getScan() {
    if (argumentCase_ == 4) {
       return (com.scalar.db.rpc.Scan) argument_;
    }
    return com.scalar.db.rpc.Scan.getDefaultInstance();
  }
  /**
   * <code>.rpc.Scan scan = 4;</code>
   */
  @java.lang.Override
  public com.scalar.db.rpc.ScanOrBuilder getScanOrBuilder() {
    if (argumentCase_ == 4) {
       return (com.scalar.db.rpc.Scan) argument_;
    }
    return com.scalar.db.rpc.Scan.getDefaultInstance();
  }

  public static final int MUTATIONS_FIELD_NUMBER = 5;
  /**
   * <code>.rpc.TransactionRequest.Mutations mutations = 5;</code>
   * @return Whether the mutations field is set.
   */
  @java.lang.Override
  public boolean hasMutations() {
    return argumentCase_ == 5;
  }
  /**
   * <code>.rpc.TransactionRequest.Mutations mutations = 5;</code>
   * @return The mutations.
   */
  @java.lang.Override
  public com.scalar.db.rpc.TransactionRequest.Mutations getMutations() {
    if (argumentCase_ == 5) {
       return (com.scalar.db.rpc.TransactionRequest.Mutations) argument_;
    }
    return com.scalar.db.rpc.TransactionRequest.Mutations.getDefaultInstance();
  }
  /**
   * <code>.rpc.TransactionRequest.Mutations mutations = 5;</code>
   */
  @java.lang.Override
  public com.scalar.db.rpc.TransactionRequest.MutationsOrBuilder getMutationsOrBuilder() {
    if (argumentCase_ == 5) {
       return (com.scalar.db.rpc.TransactionRequest.Mutations) argument_;
    }
    return com.scalar.db.rpc.TransactionRequest.Mutations.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (command_ != com.scalar.db.rpc.TransactionRequest.Command.START.getNumber()) {
      output.writeEnum(1, command_);
    }
    if (argumentCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, argument_);
    }
    if (argumentCase_ == 3) {
      output.writeMessage(3, (com.scalar.db.rpc.Get) argument_);
    }
    if (argumentCase_ == 4) {
      output.writeMessage(4, (com.scalar.db.rpc.Scan) argument_);
    }
    if (argumentCase_ == 5) {
      output.writeMessage(5, (com.scalar.db.rpc.TransactionRequest.Mutations) argument_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (command_ != com.scalar.db.rpc.TransactionRequest.Command.START.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, command_);
    }
    if (argumentCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, argument_);
    }
    if (argumentCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.scalar.db.rpc.Get) argument_);
    }
    if (argumentCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.scalar.db.rpc.Scan) argument_);
    }
    if (argumentCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.scalar.db.rpc.TransactionRequest.Mutations) argument_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scalar.db.rpc.TransactionRequest)) {
      return super.equals(obj);
    }
    com.scalar.db.rpc.TransactionRequest other = (com.scalar.db.rpc.TransactionRequest) obj;

    if (command_ != other.command_) return false;
    if (!getArgumentCase().equals(other.getArgumentCase())) return false;
    switch (argumentCase_) {
      case 2:
        if (!getTransactionId()
            .equals(other.getTransactionId())) return false;
        break;
      case 3:
        if (!getGet()
            .equals(other.getGet())) return false;
        break;
      case 4:
        if (!getScan()
            .equals(other.getScan())) return false;
        break;
      case 5:
        if (!getMutations()
            .equals(other.getMutations())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMAND_FIELD_NUMBER;
    hash = (53 * hash) + command_;
    switch (argumentCase_) {
      case 2:
        hash = (37 * hash) + TRANSACTION_ID_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionId().hashCode();
        break;
      case 3:
        hash = (37 * hash) + GET_FIELD_NUMBER;
        hash = (53 * hash) + getGet().hashCode();
        break;
      case 4:
        hash = (37 * hash) + SCAN_FIELD_NUMBER;
        hash = (53 * hash) + getScan().hashCode();
        break;
      case 5:
        hash = (37 * hash) + MUTATIONS_FIELD_NUMBER;
        hash = (53 * hash) + getMutations().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scalar.db.rpc.TransactionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scalar.db.rpc.TransactionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.scalar.db.rpc.TransactionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scalar.db.rpc.TransactionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc.TransactionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.TransactionRequest)
      com.scalar.db.rpc.TransactionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scalar.db.rpc.ScalarDbProto.internal_static_rpc_TransactionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scalar.db.rpc.ScalarDbProto.internal_static_rpc_TransactionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scalar.db.rpc.TransactionRequest.class, com.scalar.db.rpc.TransactionRequest.Builder.class);
    }

    // Construct using com.scalar.db.rpc.TransactionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      command_ = 0;

      argumentCase_ = 0;
      argument_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scalar.db.rpc.ScalarDbProto.internal_static_rpc_TransactionRequest_descriptor;
    }

    @java.lang.Override
    public com.scalar.db.rpc.TransactionRequest getDefaultInstanceForType() {
      return com.scalar.db.rpc.TransactionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.scalar.db.rpc.TransactionRequest build() {
      com.scalar.db.rpc.TransactionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scalar.db.rpc.TransactionRequest buildPartial() {
      com.scalar.db.rpc.TransactionRequest result = new com.scalar.db.rpc.TransactionRequest(this);
      result.command_ = command_;
      if (argumentCase_ == 2) {
        result.argument_ = argument_;
      }
      if (argumentCase_ == 3) {
        if (getBuilder_ == null) {
          result.argument_ = argument_;
        } else {
          result.argument_ = getBuilder_.build();
        }
      }
      if (argumentCase_ == 4) {
        if (scanBuilder_ == null) {
          result.argument_ = argument_;
        } else {
          result.argument_ = scanBuilder_.build();
        }
      }
      if (argumentCase_ == 5) {
        if (mutationsBuilder_ == null) {
          result.argument_ = argument_;
        } else {
          result.argument_ = mutationsBuilder_.build();
        }
      }
      result.argumentCase_ = argumentCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scalar.db.rpc.TransactionRequest) {
        return mergeFrom((com.scalar.db.rpc.TransactionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scalar.db.rpc.TransactionRequest other) {
      if (other == com.scalar.db.rpc.TransactionRequest.getDefaultInstance()) return this;
      if (other.command_ != 0) {
        setCommandValue(other.getCommandValue());
      }
      switch (other.getArgumentCase()) {
        case TRANSACTION_ID: {
          argumentCase_ = 2;
          argument_ = other.argument_;
          onChanged();
          break;
        }
        case GET: {
          mergeGet(other.getGet());
          break;
        }
        case SCAN: {
          mergeScan(other.getScan());
          break;
        }
        case MUTATIONS: {
          mergeMutations(other.getMutations());
          break;
        }
        case ARGUMENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.scalar.db.rpc.TransactionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.scalar.db.rpc.TransactionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int argumentCase_ = 0;
    private java.lang.Object argument_;
    public ArgumentCase
        getArgumentCase() {
      return ArgumentCase.forNumber(
          argumentCase_);
    }

    public Builder clearArgument() {
      argumentCase_ = 0;
      argument_ = null;
      onChanged();
      return this;
    }


    private int command_ = 0;
    /**
     * <code>.rpc.TransactionRequest.Command command = 1;</code>
     * @return The enum numeric value on the wire for command.
     */
    @java.lang.Override public int getCommandValue() {
      return command_;
    }
    /**
     * <code>.rpc.TransactionRequest.Command command = 1;</code>
     * @param value The enum numeric value on the wire for command to set.
     * @return This builder for chaining.
     */
    public Builder setCommandValue(int value) {
      
      command_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.rpc.TransactionRequest.Command command = 1;</code>
     * @return The command.
     */
    @java.lang.Override
    public com.scalar.db.rpc.TransactionRequest.Command getCommand() {
      @SuppressWarnings("deprecation")
      com.scalar.db.rpc.TransactionRequest.Command result = com.scalar.db.rpc.TransactionRequest.Command.valueOf(command_);
      return result == null ? com.scalar.db.rpc.TransactionRequest.Command.UNRECOGNIZED : result;
    }
    /**
     * <code>.rpc.TransactionRequest.Command command = 1;</code>
     * @param value The command to set.
     * @return This builder for chaining.
     */
    public Builder setCommand(com.scalar.db.rpc.TransactionRequest.Command value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      command_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.rpc.TransactionRequest.Command command = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommand() {
      
      command_ = 0;
      onChanged();
      return this;
    }

    /**
     * <code>string transaction_id = 2;</code>
     * @return Whether the transactionId field is set.
     */
    @java.lang.Override
    public boolean hasTransactionId() {
      return argumentCase_ == 2;
    }
    /**
     * <code>string transaction_id = 2;</code>
     * @return The transactionId.
     */
    @java.lang.Override
    public java.lang.String getTransactionId() {
      java.lang.Object ref = "";
      if (argumentCase_ == 2) {
        ref = argument_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (argumentCase_ == 2) {
          argument_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transaction_id = 2;</code>
     * @return The bytes for transactionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTransactionIdBytes() {
      java.lang.Object ref = "";
      if (argumentCase_ == 2) {
        ref = argument_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (argumentCase_ == 2) {
          argument_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transaction_id = 2;</code>
     * @param value The transactionId to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  argumentCase_ = 2;
      argument_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string transaction_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionId() {
      if (argumentCase_ == 2) {
        argumentCase_ = 0;
        argument_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string transaction_id = 2;</code>
     * @param value The bytes for transactionId to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      argumentCase_ = 2;
      argument_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.Get, com.scalar.db.rpc.Get.Builder, com.scalar.db.rpc.GetOrBuilder> getBuilder_;
    /**
     * <code>.rpc.Get get = 3;</code>
     * @return Whether the get field is set.
     */
    @java.lang.Override
    public boolean hasGet() {
      return argumentCase_ == 3;
    }
    /**
     * <code>.rpc.Get get = 3;</code>
     * @return The get.
     */
    @java.lang.Override
    public com.scalar.db.rpc.Get getGet() {
      if (getBuilder_ == null) {
        if (argumentCase_ == 3) {
          return (com.scalar.db.rpc.Get) argument_;
        }
        return com.scalar.db.rpc.Get.getDefaultInstance();
      } else {
        if (argumentCase_ == 3) {
          return getBuilder_.getMessage();
        }
        return com.scalar.db.rpc.Get.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.Get get = 3;</code>
     */
    public Builder setGet(com.scalar.db.rpc.Get value) {
      if (getBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        argument_ = value;
        onChanged();
      } else {
        getBuilder_.setMessage(value);
      }
      argumentCase_ = 3;
      return this;
    }
    /**
     * <code>.rpc.Get get = 3;</code>
     */
    public Builder setGet(
        com.scalar.db.rpc.Get.Builder builderForValue) {
      if (getBuilder_ == null) {
        argument_ = builderForValue.build();
        onChanged();
      } else {
        getBuilder_.setMessage(builderForValue.build());
      }
      argumentCase_ = 3;
      return this;
    }
    /**
     * <code>.rpc.Get get = 3;</code>
     */
    public Builder mergeGet(com.scalar.db.rpc.Get value) {
      if (getBuilder_ == null) {
        if (argumentCase_ == 3 &&
            argument_ != com.scalar.db.rpc.Get.getDefaultInstance()) {
          argument_ = com.scalar.db.rpc.Get.newBuilder((com.scalar.db.rpc.Get) argument_)
              .mergeFrom(value).buildPartial();
        } else {
          argument_ = value;
        }
        onChanged();
      } else {
        if (argumentCase_ == 3) {
          getBuilder_.mergeFrom(value);
        }
        getBuilder_.setMessage(value);
      }
      argumentCase_ = 3;
      return this;
    }
    /**
     * <code>.rpc.Get get = 3;</code>
     */
    public Builder clearGet() {
      if (getBuilder_ == null) {
        if (argumentCase_ == 3) {
          argumentCase_ = 0;
          argument_ = null;
          onChanged();
        }
      } else {
        if (argumentCase_ == 3) {
          argumentCase_ = 0;
          argument_ = null;
        }
        getBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.rpc.Get get = 3;</code>
     */
    public com.scalar.db.rpc.Get.Builder getGetBuilder() {
      return getGetFieldBuilder().getBuilder();
    }
    /**
     * <code>.rpc.Get get = 3;</code>
     */
    @java.lang.Override
    public com.scalar.db.rpc.GetOrBuilder getGetOrBuilder() {
      if ((argumentCase_ == 3) && (getBuilder_ != null)) {
        return getBuilder_.getMessageOrBuilder();
      } else {
        if (argumentCase_ == 3) {
          return (com.scalar.db.rpc.Get) argument_;
        }
        return com.scalar.db.rpc.Get.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.Get get = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.Get, com.scalar.db.rpc.Get.Builder, com.scalar.db.rpc.GetOrBuilder> 
        getGetFieldBuilder() {
      if (getBuilder_ == null) {
        if (!(argumentCase_ == 3)) {
          argument_ = com.scalar.db.rpc.Get.getDefaultInstance();
        }
        getBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.scalar.db.rpc.Get, com.scalar.db.rpc.Get.Builder, com.scalar.db.rpc.GetOrBuilder>(
                (com.scalar.db.rpc.Get) argument_,
                getParentForChildren(),
                isClean());
        argument_ = null;
      }
      argumentCase_ = 3;
      onChanged();;
      return getBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.Scan, com.scalar.db.rpc.Scan.Builder, com.scalar.db.rpc.ScanOrBuilder> scanBuilder_;
    /**
     * <code>.rpc.Scan scan = 4;</code>
     * @return Whether the scan field is set.
     */
    @java.lang.Override
    public boolean hasScan() {
      return argumentCase_ == 4;
    }
    /**
     * <code>.rpc.Scan scan = 4;</code>
     * @return The scan.
     */
    @java.lang.Override
    public com.scalar.db.rpc.Scan getScan() {
      if (scanBuilder_ == null) {
        if (argumentCase_ == 4) {
          return (com.scalar.db.rpc.Scan) argument_;
        }
        return com.scalar.db.rpc.Scan.getDefaultInstance();
      } else {
        if (argumentCase_ == 4) {
          return scanBuilder_.getMessage();
        }
        return com.scalar.db.rpc.Scan.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.Scan scan = 4;</code>
     */
    public Builder setScan(com.scalar.db.rpc.Scan value) {
      if (scanBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        argument_ = value;
        onChanged();
      } else {
        scanBuilder_.setMessage(value);
      }
      argumentCase_ = 4;
      return this;
    }
    /**
     * <code>.rpc.Scan scan = 4;</code>
     */
    public Builder setScan(
        com.scalar.db.rpc.Scan.Builder builderForValue) {
      if (scanBuilder_ == null) {
        argument_ = builderForValue.build();
        onChanged();
      } else {
        scanBuilder_.setMessage(builderForValue.build());
      }
      argumentCase_ = 4;
      return this;
    }
    /**
     * <code>.rpc.Scan scan = 4;</code>
     */
    public Builder mergeScan(com.scalar.db.rpc.Scan value) {
      if (scanBuilder_ == null) {
        if (argumentCase_ == 4 &&
            argument_ != com.scalar.db.rpc.Scan.getDefaultInstance()) {
          argument_ = com.scalar.db.rpc.Scan.newBuilder((com.scalar.db.rpc.Scan) argument_)
              .mergeFrom(value).buildPartial();
        } else {
          argument_ = value;
        }
        onChanged();
      } else {
        if (argumentCase_ == 4) {
          scanBuilder_.mergeFrom(value);
        }
        scanBuilder_.setMessage(value);
      }
      argumentCase_ = 4;
      return this;
    }
    /**
     * <code>.rpc.Scan scan = 4;</code>
     */
    public Builder clearScan() {
      if (scanBuilder_ == null) {
        if (argumentCase_ == 4) {
          argumentCase_ = 0;
          argument_ = null;
          onChanged();
        }
      } else {
        if (argumentCase_ == 4) {
          argumentCase_ = 0;
          argument_ = null;
        }
        scanBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.rpc.Scan scan = 4;</code>
     */
    public com.scalar.db.rpc.Scan.Builder getScanBuilder() {
      return getScanFieldBuilder().getBuilder();
    }
    /**
     * <code>.rpc.Scan scan = 4;</code>
     */
    @java.lang.Override
    public com.scalar.db.rpc.ScanOrBuilder getScanOrBuilder() {
      if ((argumentCase_ == 4) && (scanBuilder_ != null)) {
        return scanBuilder_.getMessageOrBuilder();
      } else {
        if (argumentCase_ == 4) {
          return (com.scalar.db.rpc.Scan) argument_;
        }
        return com.scalar.db.rpc.Scan.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.Scan scan = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.Scan, com.scalar.db.rpc.Scan.Builder, com.scalar.db.rpc.ScanOrBuilder> 
        getScanFieldBuilder() {
      if (scanBuilder_ == null) {
        if (!(argumentCase_ == 4)) {
          argument_ = com.scalar.db.rpc.Scan.getDefaultInstance();
        }
        scanBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.scalar.db.rpc.Scan, com.scalar.db.rpc.Scan.Builder, com.scalar.db.rpc.ScanOrBuilder>(
                (com.scalar.db.rpc.Scan) argument_,
                getParentForChildren(),
                isClean());
        argument_ = null;
      }
      argumentCase_ = 4;
      onChanged();;
      return scanBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.TransactionRequest.Mutations, com.scalar.db.rpc.TransactionRequest.Mutations.Builder, com.scalar.db.rpc.TransactionRequest.MutationsOrBuilder> mutationsBuilder_;
    /**
     * <code>.rpc.TransactionRequest.Mutations mutations = 5;</code>
     * @return Whether the mutations field is set.
     */
    @java.lang.Override
    public boolean hasMutations() {
      return argumentCase_ == 5;
    }
    /**
     * <code>.rpc.TransactionRequest.Mutations mutations = 5;</code>
     * @return The mutations.
     */
    @java.lang.Override
    public com.scalar.db.rpc.TransactionRequest.Mutations getMutations() {
      if (mutationsBuilder_ == null) {
        if (argumentCase_ == 5) {
          return (com.scalar.db.rpc.TransactionRequest.Mutations) argument_;
        }
        return com.scalar.db.rpc.TransactionRequest.Mutations.getDefaultInstance();
      } else {
        if (argumentCase_ == 5) {
          return mutationsBuilder_.getMessage();
        }
        return com.scalar.db.rpc.TransactionRequest.Mutations.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.TransactionRequest.Mutations mutations = 5;</code>
     */
    public Builder setMutations(com.scalar.db.rpc.TransactionRequest.Mutations value) {
      if (mutationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        argument_ = value;
        onChanged();
      } else {
        mutationsBuilder_.setMessage(value);
      }
      argumentCase_ = 5;
      return this;
    }
    /**
     * <code>.rpc.TransactionRequest.Mutations mutations = 5;</code>
     */
    public Builder setMutations(
        com.scalar.db.rpc.TransactionRequest.Mutations.Builder builderForValue) {
      if (mutationsBuilder_ == null) {
        argument_ = builderForValue.build();
        onChanged();
      } else {
        mutationsBuilder_.setMessage(builderForValue.build());
      }
      argumentCase_ = 5;
      return this;
    }
    /**
     * <code>.rpc.TransactionRequest.Mutations mutations = 5;</code>
     */
    public Builder mergeMutations(com.scalar.db.rpc.TransactionRequest.Mutations value) {
      if (mutationsBuilder_ == null) {
        if (argumentCase_ == 5 &&
            argument_ != com.scalar.db.rpc.TransactionRequest.Mutations.getDefaultInstance()) {
          argument_ = com.scalar.db.rpc.TransactionRequest.Mutations.newBuilder((com.scalar.db.rpc.TransactionRequest.Mutations) argument_)
              .mergeFrom(value).buildPartial();
        } else {
          argument_ = value;
        }
        onChanged();
      } else {
        if (argumentCase_ == 5) {
          mutationsBuilder_.mergeFrom(value);
        }
        mutationsBuilder_.setMessage(value);
      }
      argumentCase_ = 5;
      return this;
    }
    /**
     * <code>.rpc.TransactionRequest.Mutations mutations = 5;</code>
     */
    public Builder clearMutations() {
      if (mutationsBuilder_ == null) {
        if (argumentCase_ == 5) {
          argumentCase_ = 0;
          argument_ = null;
          onChanged();
        }
      } else {
        if (argumentCase_ == 5) {
          argumentCase_ = 0;
          argument_ = null;
        }
        mutationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.rpc.TransactionRequest.Mutations mutations = 5;</code>
     */
    public com.scalar.db.rpc.TransactionRequest.Mutations.Builder getMutationsBuilder() {
      return getMutationsFieldBuilder().getBuilder();
    }
    /**
     * <code>.rpc.TransactionRequest.Mutations mutations = 5;</code>
     */
    @java.lang.Override
    public com.scalar.db.rpc.TransactionRequest.MutationsOrBuilder getMutationsOrBuilder() {
      if ((argumentCase_ == 5) && (mutationsBuilder_ != null)) {
        return mutationsBuilder_.getMessageOrBuilder();
      } else {
        if (argumentCase_ == 5) {
          return (com.scalar.db.rpc.TransactionRequest.Mutations) argument_;
        }
        return com.scalar.db.rpc.TransactionRequest.Mutations.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.TransactionRequest.Mutations mutations = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.TransactionRequest.Mutations, com.scalar.db.rpc.TransactionRequest.Mutations.Builder, com.scalar.db.rpc.TransactionRequest.MutationsOrBuilder> 
        getMutationsFieldBuilder() {
      if (mutationsBuilder_ == null) {
        if (!(argumentCase_ == 5)) {
          argument_ = com.scalar.db.rpc.TransactionRequest.Mutations.getDefaultInstance();
        }
        mutationsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.scalar.db.rpc.TransactionRequest.Mutations, com.scalar.db.rpc.TransactionRequest.Mutations.Builder, com.scalar.db.rpc.TransactionRequest.MutationsOrBuilder>(
                (com.scalar.db.rpc.TransactionRequest.Mutations) argument_,
                getParentForChildren(),
                isClean());
        argument_ = null;
      }
      argumentCase_ = 5;
      onChanged();;
      return mutationsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.TransactionRequest)
  }

  // @@protoc_insertion_point(class_scope:rpc.TransactionRequest)
  private static final com.scalar.db.rpc.TransactionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scalar.db.rpc.TransactionRequest();
  }

  public static com.scalar.db.rpc.TransactionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransactionRequest>
      PARSER = new com.google.protobuf.AbstractParser<TransactionRequest>() {
    @java.lang.Override
    public TransactionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TransactionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransactionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransactionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scalar.db.rpc.TransactionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

