// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalardb.proto

package com.scalar.db.rpc;

/**
 * Protobuf type {@code rpc.TransactionRequest}
 */
public final class TransactionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.TransactionRequest)
    TransactionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransactionRequest.newBuilder() to construct.
  private TransactionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransactionRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TransactionRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransactionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.scalar.db.rpc.StartTransactionRequest.Builder subBuilder = null;
            if (requestCase_ == 1) {
              subBuilder = ((com.scalar.db.rpc.StartTransactionRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(com.scalar.db.rpc.StartTransactionRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.scalar.db.rpc.StartTransactionRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 1;
            break;
          }
          case 18: {
            com.scalar.db.rpc.TransactionalGetRequest.Builder subBuilder = null;
            if (requestCase_ == 2) {
              subBuilder = ((com.scalar.db.rpc.TransactionalGetRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(com.scalar.db.rpc.TransactionalGetRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.scalar.db.rpc.TransactionalGetRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 2;
            break;
          }
          case 26: {
            com.scalar.db.rpc.TransactionalScanRequest.Builder subBuilder = null;
            if (requestCase_ == 3) {
              subBuilder = ((com.scalar.db.rpc.TransactionalScanRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(com.scalar.db.rpc.TransactionalScanRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.scalar.db.rpc.TransactionalScanRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 3;
            break;
          }
          case 34: {
            com.scalar.db.rpc.TransactionalMutateRequest.Builder subBuilder = null;
            if (requestCase_ == 4) {
              subBuilder = ((com.scalar.db.rpc.TransactionalMutateRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(com.scalar.db.rpc.TransactionalMutateRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.scalar.db.rpc.TransactionalMutateRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 4;
            break;
          }
          case 42: {
            com.scalar.db.rpc.CommitRequest.Builder subBuilder = null;
            if (requestCase_ == 5) {
              subBuilder = ((com.scalar.db.rpc.CommitRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(com.scalar.db.rpc.CommitRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.scalar.db.rpc.CommitRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 5;
            break;
          }
          case 50: {
            com.scalar.db.rpc.AbortRequest.Builder subBuilder = null;
            if (requestCase_ == 6) {
              subBuilder = ((com.scalar.db.rpc.AbortRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(com.scalar.db.rpc.AbortRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.scalar.db.rpc.AbortRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 6;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scalar.db.rpc.ScalarDbProto.internal_static_rpc_TransactionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scalar.db.rpc.ScalarDbProto.internal_static_rpc_TransactionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scalar.db.rpc.TransactionRequest.class, com.scalar.db.rpc.TransactionRequest.Builder.class);
  }

  private int requestCase_ = 0;
  private java.lang.Object request_;
  public enum RequestCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    START_TRANSACTION_REQUEST(1),
    TRANSACTIONAL_GET_REQUEST(2),
    TRANSACTIONAL_SCAN_REQUEST(3),
    TRANSACTIONAL_MUTATE_REQUEST(4),
    COMMIT_REQUEST(5),
    ABORT_REQUEST(6),
    REQUEST_NOT_SET(0);
    private final int value;
    private RequestCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static RequestCase forNumber(int value) {
      switch (value) {
        case 1: return START_TRANSACTION_REQUEST;
        case 2: return TRANSACTIONAL_GET_REQUEST;
        case 3: return TRANSACTIONAL_SCAN_REQUEST;
        case 4: return TRANSACTIONAL_MUTATE_REQUEST;
        case 5: return COMMIT_REQUEST;
        case 6: return ABORT_REQUEST;
        case 0: return REQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public RequestCase
  getRequestCase() {
    return RequestCase.forNumber(
        requestCase_);
  }

  public static final int START_TRANSACTION_REQUEST_FIELD_NUMBER = 1;
  /**
   * <code>.rpc.StartTransactionRequest start_transaction_request = 1;</code>
   * @return Whether the startTransactionRequest field is set.
   */
  @java.lang.Override
  public boolean hasStartTransactionRequest() {
    return requestCase_ == 1;
  }
  /**
   * <code>.rpc.StartTransactionRequest start_transaction_request = 1;</code>
   * @return The startTransactionRequest.
   */
  @java.lang.Override
  public com.scalar.db.rpc.StartTransactionRequest getStartTransactionRequest() {
    if (requestCase_ == 1) {
       return (com.scalar.db.rpc.StartTransactionRequest) request_;
    }
    return com.scalar.db.rpc.StartTransactionRequest.getDefaultInstance();
  }
  /**
   * <code>.rpc.StartTransactionRequest start_transaction_request = 1;</code>
   */
  @java.lang.Override
  public com.scalar.db.rpc.StartTransactionRequestOrBuilder getStartTransactionRequestOrBuilder() {
    if (requestCase_ == 1) {
       return (com.scalar.db.rpc.StartTransactionRequest) request_;
    }
    return com.scalar.db.rpc.StartTransactionRequest.getDefaultInstance();
  }

  public static final int TRANSACTIONAL_GET_REQUEST_FIELD_NUMBER = 2;
  /**
   * <code>.rpc.TransactionalGetRequest transactional_get_request = 2;</code>
   * @return Whether the transactionalGetRequest field is set.
   */
  @java.lang.Override
  public boolean hasTransactionalGetRequest() {
    return requestCase_ == 2;
  }
  /**
   * <code>.rpc.TransactionalGetRequest transactional_get_request = 2;</code>
   * @return The transactionalGetRequest.
   */
  @java.lang.Override
  public com.scalar.db.rpc.TransactionalGetRequest getTransactionalGetRequest() {
    if (requestCase_ == 2) {
       return (com.scalar.db.rpc.TransactionalGetRequest) request_;
    }
    return com.scalar.db.rpc.TransactionalGetRequest.getDefaultInstance();
  }
  /**
   * <code>.rpc.TransactionalGetRequest transactional_get_request = 2;</code>
   */
  @java.lang.Override
  public com.scalar.db.rpc.TransactionalGetRequestOrBuilder getTransactionalGetRequestOrBuilder() {
    if (requestCase_ == 2) {
       return (com.scalar.db.rpc.TransactionalGetRequest) request_;
    }
    return com.scalar.db.rpc.TransactionalGetRequest.getDefaultInstance();
  }

  public static final int TRANSACTIONAL_SCAN_REQUEST_FIELD_NUMBER = 3;
  /**
   * <code>.rpc.TransactionalScanRequest transactional_scan_request = 3;</code>
   * @return Whether the transactionalScanRequest field is set.
   */
  @java.lang.Override
  public boolean hasTransactionalScanRequest() {
    return requestCase_ == 3;
  }
  /**
   * <code>.rpc.TransactionalScanRequest transactional_scan_request = 3;</code>
   * @return The transactionalScanRequest.
   */
  @java.lang.Override
  public com.scalar.db.rpc.TransactionalScanRequest getTransactionalScanRequest() {
    if (requestCase_ == 3) {
       return (com.scalar.db.rpc.TransactionalScanRequest) request_;
    }
    return com.scalar.db.rpc.TransactionalScanRequest.getDefaultInstance();
  }
  /**
   * <code>.rpc.TransactionalScanRequest transactional_scan_request = 3;</code>
   */
  @java.lang.Override
  public com.scalar.db.rpc.TransactionalScanRequestOrBuilder getTransactionalScanRequestOrBuilder() {
    if (requestCase_ == 3) {
       return (com.scalar.db.rpc.TransactionalScanRequest) request_;
    }
    return com.scalar.db.rpc.TransactionalScanRequest.getDefaultInstance();
  }

  public static final int TRANSACTIONAL_MUTATE_REQUEST_FIELD_NUMBER = 4;
  /**
   * <code>.rpc.TransactionalMutateRequest transactional_mutate_request = 4;</code>
   * @return Whether the transactionalMutateRequest field is set.
   */
  @java.lang.Override
  public boolean hasTransactionalMutateRequest() {
    return requestCase_ == 4;
  }
  /**
   * <code>.rpc.TransactionalMutateRequest transactional_mutate_request = 4;</code>
   * @return The transactionalMutateRequest.
   */
  @java.lang.Override
  public com.scalar.db.rpc.TransactionalMutateRequest getTransactionalMutateRequest() {
    if (requestCase_ == 4) {
       return (com.scalar.db.rpc.TransactionalMutateRequest) request_;
    }
    return com.scalar.db.rpc.TransactionalMutateRequest.getDefaultInstance();
  }
  /**
   * <code>.rpc.TransactionalMutateRequest transactional_mutate_request = 4;</code>
   */
  @java.lang.Override
  public com.scalar.db.rpc.TransactionalMutateRequestOrBuilder getTransactionalMutateRequestOrBuilder() {
    if (requestCase_ == 4) {
       return (com.scalar.db.rpc.TransactionalMutateRequest) request_;
    }
    return com.scalar.db.rpc.TransactionalMutateRequest.getDefaultInstance();
  }

  public static final int COMMIT_REQUEST_FIELD_NUMBER = 5;
  /**
   * <code>.rpc.CommitRequest commit_request = 5;</code>
   * @return Whether the commitRequest field is set.
   */
  @java.lang.Override
  public boolean hasCommitRequest() {
    return requestCase_ == 5;
  }
  /**
   * <code>.rpc.CommitRequest commit_request = 5;</code>
   * @return The commitRequest.
   */
  @java.lang.Override
  public com.scalar.db.rpc.CommitRequest getCommitRequest() {
    if (requestCase_ == 5) {
       return (com.scalar.db.rpc.CommitRequest) request_;
    }
    return com.scalar.db.rpc.CommitRequest.getDefaultInstance();
  }
  /**
   * <code>.rpc.CommitRequest commit_request = 5;</code>
   */
  @java.lang.Override
  public com.scalar.db.rpc.CommitRequestOrBuilder getCommitRequestOrBuilder() {
    if (requestCase_ == 5) {
       return (com.scalar.db.rpc.CommitRequest) request_;
    }
    return com.scalar.db.rpc.CommitRequest.getDefaultInstance();
  }

  public static final int ABORT_REQUEST_FIELD_NUMBER = 6;
  /**
   * <code>.rpc.AbortRequest abort_request = 6;</code>
   * @return Whether the abortRequest field is set.
   */
  @java.lang.Override
  public boolean hasAbortRequest() {
    return requestCase_ == 6;
  }
  /**
   * <code>.rpc.AbortRequest abort_request = 6;</code>
   * @return The abortRequest.
   */
  @java.lang.Override
  public com.scalar.db.rpc.AbortRequest getAbortRequest() {
    if (requestCase_ == 6) {
       return (com.scalar.db.rpc.AbortRequest) request_;
    }
    return com.scalar.db.rpc.AbortRequest.getDefaultInstance();
  }
  /**
   * <code>.rpc.AbortRequest abort_request = 6;</code>
   */
  @java.lang.Override
  public com.scalar.db.rpc.AbortRequestOrBuilder getAbortRequestOrBuilder() {
    if (requestCase_ == 6) {
       return (com.scalar.db.rpc.AbortRequest) request_;
    }
    return com.scalar.db.rpc.AbortRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestCase_ == 1) {
      output.writeMessage(1, (com.scalar.db.rpc.StartTransactionRequest) request_);
    }
    if (requestCase_ == 2) {
      output.writeMessage(2, (com.scalar.db.rpc.TransactionalGetRequest) request_);
    }
    if (requestCase_ == 3) {
      output.writeMessage(3, (com.scalar.db.rpc.TransactionalScanRequest) request_);
    }
    if (requestCase_ == 4) {
      output.writeMessage(4, (com.scalar.db.rpc.TransactionalMutateRequest) request_);
    }
    if (requestCase_ == 5) {
      output.writeMessage(5, (com.scalar.db.rpc.CommitRequest) request_);
    }
    if (requestCase_ == 6) {
      output.writeMessage(6, (com.scalar.db.rpc.AbortRequest) request_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.scalar.db.rpc.StartTransactionRequest) request_);
    }
    if (requestCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.scalar.db.rpc.TransactionalGetRequest) request_);
    }
    if (requestCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.scalar.db.rpc.TransactionalScanRequest) request_);
    }
    if (requestCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.scalar.db.rpc.TransactionalMutateRequest) request_);
    }
    if (requestCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.scalar.db.rpc.CommitRequest) request_);
    }
    if (requestCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.scalar.db.rpc.AbortRequest) request_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scalar.db.rpc.TransactionRequest)) {
      return super.equals(obj);
    }
    com.scalar.db.rpc.TransactionRequest other = (com.scalar.db.rpc.TransactionRequest) obj;

    if (!getRequestCase().equals(other.getRequestCase())) return false;
    switch (requestCase_) {
      case 1:
        if (!getStartTransactionRequest()
            .equals(other.getStartTransactionRequest())) return false;
        break;
      case 2:
        if (!getTransactionalGetRequest()
            .equals(other.getTransactionalGetRequest())) return false;
        break;
      case 3:
        if (!getTransactionalScanRequest()
            .equals(other.getTransactionalScanRequest())) return false;
        break;
      case 4:
        if (!getTransactionalMutateRequest()
            .equals(other.getTransactionalMutateRequest())) return false;
        break;
      case 5:
        if (!getCommitRequest()
            .equals(other.getCommitRequest())) return false;
        break;
      case 6:
        if (!getAbortRequest()
            .equals(other.getAbortRequest())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (requestCase_) {
      case 1:
        hash = (37 * hash) + START_TRANSACTION_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getStartTransactionRequest().hashCode();
        break;
      case 2:
        hash = (37 * hash) + TRANSACTIONAL_GET_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionalGetRequest().hashCode();
        break;
      case 3:
        hash = (37 * hash) + TRANSACTIONAL_SCAN_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionalScanRequest().hashCode();
        break;
      case 4:
        hash = (37 * hash) + TRANSACTIONAL_MUTATE_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionalMutateRequest().hashCode();
        break;
      case 5:
        hash = (37 * hash) + COMMIT_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getCommitRequest().hashCode();
        break;
      case 6:
        hash = (37 * hash) + ABORT_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getAbortRequest().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scalar.db.rpc.TransactionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scalar.db.rpc.TransactionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.scalar.db.rpc.TransactionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalar.db.rpc.TransactionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scalar.db.rpc.TransactionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc.TransactionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.TransactionRequest)
      com.scalar.db.rpc.TransactionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scalar.db.rpc.ScalarDbProto.internal_static_rpc_TransactionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scalar.db.rpc.ScalarDbProto.internal_static_rpc_TransactionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scalar.db.rpc.TransactionRequest.class, com.scalar.db.rpc.TransactionRequest.Builder.class);
    }

    // Construct using com.scalar.db.rpc.TransactionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestCase_ = 0;
      request_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scalar.db.rpc.ScalarDbProto.internal_static_rpc_TransactionRequest_descriptor;
    }

    @java.lang.Override
    public com.scalar.db.rpc.TransactionRequest getDefaultInstanceForType() {
      return com.scalar.db.rpc.TransactionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.scalar.db.rpc.TransactionRequest build() {
      com.scalar.db.rpc.TransactionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scalar.db.rpc.TransactionRequest buildPartial() {
      com.scalar.db.rpc.TransactionRequest result = new com.scalar.db.rpc.TransactionRequest(this);
      if (requestCase_ == 1) {
        if (startTransactionRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = startTransactionRequestBuilder_.build();
        }
      }
      if (requestCase_ == 2) {
        if (transactionalGetRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = transactionalGetRequestBuilder_.build();
        }
      }
      if (requestCase_ == 3) {
        if (transactionalScanRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = transactionalScanRequestBuilder_.build();
        }
      }
      if (requestCase_ == 4) {
        if (transactionalMutateRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = transactionalMutateRequestBuilder_.build();
        }
      }
      if (requestCase_ == 5) {
        if (commitRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = commitRequestBuilder_.build();
        }
      }
      if (requestCase_ == 6) {
        if (abortRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = abortRequestBuilder_.build();
        }
      }
      result.requestCase_ = requestCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scalar.db.rpc.TransactionRequest) {
        return mergeFrom((com.scalar.db.rpc.TransactionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scalar.db.rpc.TransactionRequest other) {
      if (other == com.scalar.db.rpc.TransactionRequest.getDefaultInstance()) return this;
      switch (other.getRequestCase()) {
        case START_TRANSACTION_REQUEST: {
          mergeStartTransactionRequest(other.getStartTransactionRequest());
          break;
        }
        case TRANSACTIONAL_GET_REQUEST: {
          mergeTransactionalGetRequest(other.getTransactionalGetRequest());
          break;
        }
        case TRANSACTIONAL_SCAN_REQUEST: {
          mergeTransactionalScanRequest(other.getTransactionalScanRequest());
          break;
        }
        case TRANSACTIONAL_MUTATE_REQUEST: {
          mergeTransactionalMutateRequest(other.getTransactionalMutateRequest());
          break;
        }
        case COMMIT_REQUEST: {
          mergeCommitRequest(other.getCommitRequest());
          break;
        }
        case ABORT_REQUEST: {
          mergeAbortRequest(other.getAbortRequest());
          break;
        }
        case REQUEST_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.scalar.db.rpc.TransactionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.scalar.db.rpc.TransactionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int requestCase_ = 0;
    private java.lang.Object request_;
    public RequestCase
        getRequestCase() {
      return RequestCase.forNumber(
          requestCase_);
    }

    public Builder clearRequest() {
      requestCase_ = 0;
      request_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.StartTransactionRequest, com.scalar.db.rpc.StartTransactionRequest.Builder, com.scalar.db.rpc.StartTransactionRequestOrBuilder> startTransactionRequestBuilder_;
    /**
     * <code>.rpc.StartTransactionRequest start_transaction_request = 1;</code>
     * @return Whether the startTransactionRequest field is set.
     */
    @java.lang.Override
    public boolean hasStartTransactionRequest() {
      return requestCase_ == 1;
    }
    /**
     * <code>.rpc.StartTransactionRequest start_transaction_request = 1;</code>
     * @return The startTransactionRequest.
     */
    @java.lang.Override
    public com.scalar.db.rpc.StartTransactionRequest getStartTransactionRequest() {
      if (startTransactionRequestBuilder_ == null) {
        if (requestCase_ == 1) {
          return (com.scalar.db.rpc.StartTransactionRequest) request_;
        }
        return com.scalar.db.rpc.StartTransactionRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 1) {
          return startTransactionRequestBuilder_.getMessage();
        }
        return com.scalar.db.rpc.StartTransactionRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.StartTransactionRequest start_transaction_request = 1;</code>
     */
    public Builder setStartTransactionRequest(com.scalar.db.rpc.StartTransactionRequest value) {
      if (startTransactionRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        startTransactionRequestBuilder_.setMessage(value);
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.rpc.StartTransactionRequest start_transaction_request = 1;</code>
     */
    public Builder setStartTransactionRequest(
        com.scalar.db.rpc.StartTransactionRequest.Builder builderForValue) {
      if (startTransactionRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        startTransactionRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.rpc.StartTransactionRequest start_transaction_request = 1;</code>
     */
    public Builder mergeStartTransactionRequest(com.scalar.db.rpc.StartTransactionRequest value) {
      if (startTransactionRequestBuilder_ == null) {
        if (requestCase_ == 1 &&
            request_ != com.scalar.db.rpc.StartTransactionRequest.getDefaultInstance()) {
          request_ = com.scalar.db.rpc.StartTransactionRequest.newBuilder((com.scalar.db.rpc.StartTransactionRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 1) {
          startTransactionRequestBuilder_.mergeFrom(value);
        }
        startTransactionRequestBuilder_.setMessage(value);
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.rpc.StartTransactionRequest start_transaction_request = 1;</code>
     */
    public Builder clearStartTransactionRequest() {
      if (startTransactionRequestBuilder_ == null) {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
        }
        startTransactionRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.rpc.StartTransactionRequest start_transaction_request = 1;</code>
     */
    public com.scalar.db.rpc.StartTransactionRequest.Builder getStartTransactionRequestBuilder() {
      return getStartTransactionRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.rpc.StartTransactionRequest start_transaction_request = 1;</code>
     */
    @java.lang.Override
    public com.scalar.db.rpc.StartTransactionRequestOrBuilder getStartTransactionRequestOrBuilder() {
      if ((requestCase_ == 1) && (startTransactionRequestBuilder_ != null)) {
        return startTransactionRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 1) {
          return (com.scalar.db.rpc.StartTransactionRequest) request_;
        }
        return com.scalar.db.rpc.StartTransactionRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.StartTransactionRequest start_transaction_request = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.StartTransactionRequest, com.scalar.db.rpc.StartTransactionRequest.Builder, com.scalar.db.rpc.StartTransactionRequestOrBuilder> 
        getStartTransactionRequestFieldBuilder() {
      if (startTransactionRequestBuilder_ == null) {
        if (!(requestCase_ == 1)) {
          request_ = com.scalar.db.rpc.StartTransactionRequest.getDefaultInstance();
        }
        startTransactionRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.scalar.db.rpc.StartTransactionRequest, com.scalar.db.rpc.StartTransactionRequest.Builder, com.scalar.db.rpc.StartTransactionRequestOrBuilder>(
                (com.scalar.db.rpc.StartTransactionRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 1;
      onChanged();;
      return startTransactionRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.TransactionalGetRequest, com.scalar.db.rpc.TransactionalGetRequest.Builder, com.scalar.db.rpc.TransactionalGetRequestOrBuilder> transactionalGetRequestBuilder_;
    /**
     * <code>.rpc.TransactionalGetRequest transactional_get_request = 2;</code>
     * @return Whether the transactionalGetRequest field is set.
     */
    @java.lang.Override
    public boolean hasTransactionalGetRequest() {
      return requestCase_ == 2;
    }
    /**
     * <code>.rpc.TransactionalGetRequest transactional_get_request = 2;</code>
     * @return The transactionalGetRequest.
     */
    @java.lang.Override
    public com.scalar.db.rpc.TransactionalGetRequest getTransactionalGetRequest() {
      if (transactionalGetRequestBuilder_ == null) {
        if (requestCase_ == 2) {
          return (com.scalar.db.rpc.TransactionalGetRequest) request_;
        }
        return com.scalar.db.rpc.TransactionalGetRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 2) {
          return transactionalGetRequestBuilder_.getMessage();
        }
        return com.scalar.db.rpc.TransactionalGetRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.TransactionalGetRequest transactional_get_request = 2;</code>
     */
    public Builder setTransactionalGetRequest(com.scalar.db.rpc.TransactionalGetRequest value) {
      if (transactionalGetRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        transactionalGetRequestBuilder_.setMessage(value);
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.rpc.TransactionalGetRequest transactional_get_request = 2;</code>
     */
    public Builder setTransactionalGetRequest(
        com.scalar.db.rpc.TransactionalGetRequest.Builder builderForValue) {
      if (transactionalGetRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        transactionalGetRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.rpc.TransactionalGetRequest transactional_get_request = 2;</code>
     */
    public Builder mergeTransactionalGetRequest(com.scalar.db.rpc.TransactionalGetRequest value) {
      if (transactionalGetRequestBuilder_ == null) {
        if (requestCase_ == 2 &&
            request_ != com.scalar.db.rpc.TransactionalGetRequest.getDefaultInstance()) {
          request_ = com.scalar.db.rpc.TransactionalGetRequest.newBuilder((com.scalar.db.rpc.TransactionalGetRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 2) {
          transactionalGetRequestBuilder_.mergeFrom(value);
        }
        transactionalGetRequestBuilder_.setMessage(value);
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.rpc.TransactionalGetRequest transactional_get_request = 2;</code>
     */
    public Builder clearTransactionalGetRequest() {
      if (transactionalGetRequestBuilder_ == null) {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
        }
        transactionalGetRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.rpc.TransactionalGetRequest transactional_get_request = 2;</code>
     */
    public com.scalar.db.rpc.TransactionalGetRequest.Builder getTransactionalGetRequestBuilder() {
      return getTransactionalGetRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.rpc.TransactionalGetRequest transactional_get_request = 2;</code>
     */
    @java.lang.Override
    public com.scalar.db.rpc.TransactionalGetRequestOrBuilder getTransactionalGetRequestOrBuilder() {
      if ((requestCase_ == 2) && (transactionalGetRequestBuilder_ != null)) {
        return transactionalGetRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 2) {
          return (com.scalar.db.rpc.TransactionalGetRequest) request_;
        }
        return com.scalar.db.rpc.TransactionalGetRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.TransactionalGetRequest transactional_get_request = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.TransactionalGetRequest, com.scalar.db.rpc.TransactionalGetRequest.Builder, com.scalar.db.rpc.TransactionalGetRequestOrBuilder> 
        getTransactionalGetRequestFieldBuilder() {
      if (transactionalGetRequestBuilder_ == null) {
        if (!(requestCase_ == 2)) {
          request_ = com.scalar.db.rpc.TransactionalGetRequest.getDefaultInstance();
        }
        transactionalGetRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.scalar.db.rpc.TransactionalGetRequest, com.scalar.db.rpc.TransactionalGetRequest.Builder, com.scalar.db.rpc.TransactionalGetRequestOrBuilder>(
                (com.scalar.db.rpc.TransactionalGetRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 2;
      onChanged();;
      return transactionalGetRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.TransactionalScanRequest, com.scalar.db.rpc.TransactionalScanRequest.Builder, com.scalar.db.rpc.TransactionalScanRequestOrBuilder> transactionalScanRequestBuilder_;
    /**
     * <code>.rpc.TransactionalScanRequest transactional_scan_request = 3;</code>
     * @return Whether the transactionalScanRequest field is set.
     */
    @java.lang.Override
    public boolean hasTransactionalScanRequest() {
      return requestCase_ == 3;
    }
    /**
     * <code>.rpc.TransactionalScanRequest transactional_scan_request = 3;</code>
     * @return The transactionalScanRequest.
     */
    @java.lang.Override
    public com.scalar.db.rpc.TransactionalScanRequest getTransactionalScanRequest() {
      if (transactionalScanRequestBuilder_ == null) {
        if (requestCase_ == 3) {
          return (com.scalar.db.rpc.TransactionalScanRequest) request_;
        }
        return com.scalar.db.rpc.TransactionalScanRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 3) {
          return transactionalScanRequestBuilder_.getMessage();
        }
        return com.scalar.db.rpc.TransactionalScanRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.TransactionalScanRequest transactional_scan_request = 3;</code>
     */
    public Builder setTransactionalScanRequest(com.scalar.db.rpc.TransactionalScanRequest value) {
      if (transactionalScanRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        transactionalScanRequestBuilder_.setMessage(value);
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.rpc.TransactionalScanRequest transactional_scan_request = 3;</code>
     */
    public Builder setTransactionalScanRequest(
        com.scalar.db.rpc.TransactionalScanRequest.Builder builderForValue) {
      if (transactionalScanRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        transactionalScanRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.rpc.TransactionalScanRequest transactional_scan_request = 3;</code>
     */
    public Builder mergeTransactionalScanRequest(com.scalar.db.rpc.TransactionalScanRequest value) {
      if (transactionalScanRequestBuilder_ == null) {
        if (requestCase_ == 3 &&
            request_ != com.scalar.db.rpc.TransactionalScanRequest.getDefaultInstance()) {
          request_ = com.scalar.db.rpc.TransactionalScanRequest.newBuilder((com.scalar.db.rpc.TransactionalScanRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 3) {
          transactionalScanRequestBuilder_.mergeFrom(value);
        }
        transactionalScanRequestBuilder_.setMessage(value);
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.rpc.TransactionalScanRequest transactional_scan_request = 3;</code>
     */
    public Builder clearTransactionalScanRequest() {
      if (transactionalScanRequestBuilder_ == null) {
        if (requestCase_ == 3) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 3) {
          requestCase_ = 0;
          request_ = null;
        }
        transactionalScanRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.rpc.TransactionalScanRequest transactional_scan_request = 3;</code>
     */
    public com.scalar.db.rpc.TransactionalScanRequest.Builder getTransactionalScanRequestBuilder() {
      return getTransactionalScanRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.rpc.TransactionalScanRequest transactional_scan_request = 3;</code>
     */
    @java.lang.Override
    public com.scalar.db.rpc.TransactionalScanRequestOrBuilder getTransactionalScanRequestOrBuilder() {
      if ((requestCase_ == 3) && (transactionalScanRequestBuilder_ != null)) {
        return transactionalScanRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 3) {
          return (com.scalar.db.rpc.TransactionalScanRequest) request_;
        }
        return com.scalar.db.rpc.TransactionalScanRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.TransactionalScanRequest transactional_scan_request = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.TransactionalScanRequest, com.scalar.db.rpc.TransactionalScanRequest.Builder, com.scalar.db.rpc.TransactionalScanRequestOrBuilder> 
        getTransactionalScanRequestFieldBuilder() {
      if (transactionalScanRequestBuilder_ == null) {
        if (!(requestCase_ == 3)) {
          request_ = com.scalar.db.rpc.TransactionalScanRequest.getDefaultInstance();
        }
        transactionalScanRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.scalar.db.rpc.TransactionalScanRequest, com.scalar.db.rpc.TransactionalScanRequest.Builder, com.scalar.db.rpc.TransactionalScanRequestOrBuilder>(
                (com.scalar.db.rpc.TransactionalScanRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 3;
      onChanged();;
      return transactionalScanRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.TransactionalMutateRequest, com.scalar.db.rpc.TransactionalMutateRequest.Builder, com.scalar.db.rpc.TransactionalMutateRequestOrBuilder> transactionalMutateRequestBuilder_;
    /**
     * <code>.rpc.TransactionalMutateRequest transactional_mutate_request = 4;</code>
     * @return Whether the transactionalMutateRequest field is set.
     */
    @java.lang.Override
    public boolean hasTransactionalMutateRequest() {
      return requestCase_ == 4;
    }
    /**
     * <code>.rpc.TransactionalMutateRequest transactional_mutate_request = 4;</code>
     * @return The transactionalMutateRequest.
     */
    @java.lang.Override
    public com.scalar.db.rpc.TransactionalMutateRequest getTransactionalMutateRequest() {
      if (transactionalMutateRequestBuilder_ == null) {
        if (requestCase_ == 4) {
          return (com.scalar.db.rpc.TransactionalMutateRequest) request_;
        }
        return com.scalar.db.rpc.TransactionalMutateRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 4) {
          return transactionalMutateRequestBuilder_.getMessage();
        }
        return com.scalar.db.rpc.TransactionalMutateRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.TransactionalMutateRequest transactional_mutate_request = 4;</code>
     */
    public Builder setTransactionalMutateRequest(com.scalar.db.rpc.TransactionalMutateRequest value) {
      if (transactionalMutateRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        transactionalMutateRequestBuilder_.setMessage(value);
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>.rpc.TransactionalMutateRequest transactional_mutate_request = 4;</code>
     */
    public Builder setTransactionalMutateRequest(
        com.scalar.db.rpc.TransactionalMutateRequest.Builder builderForValue) {
      if (transactionalMutateRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        transactionalMutateRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>.rpc.TransactionalMutateRequest transactional_mutate_request = 4;</code>
     */
    public Builder mergeTransactionalMutateRequest(com.scalar.db.rpc.TransactionalMutateRequest value) {
      if (transactionalMutateRequestBuilder_ == null) {
        if (requestCase_ == 4 &&
            request_ != com.scalar.db.rpc.TransactionalMutateRequest.getDefaultInstance()) {
          request_ = com.scalar.db.rpc.TransactionalMutateRequest.newBuilder((com.scalar.db.rpc.TransactionalMutateRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 4) {
          transactionalMutateRequestBuilder_.mergeFrom(value);
        }
        transactionalMutateRequestBuilder_.setMessage(value);
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>.rpc.TransactionalMutateRequest transactional_mutate_request = 4;</code>
     */
    public Builder clearTransactionalMutateRequest() {
      if (transactionalMutateRequestBuilder_ == null) {
        if (requestCase_ == 4) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 4) {
          requestCase_ = 0;
          request_ = null;
        }
        transactionalMutateRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.rpc.TransactionalMutateRequest transactional_mutate_request = 4;</code>
     */
    public com.scalar.db.rpc.TransactionalMutateRequest.Builder getTransactionalMutateRequestBuilder() {
      return getTransactionalMutateRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.rpc.TransactionalMutateRequest transactional_mutate_request = 4;</code>
     */
    @java.lang.Override
    public com.scalar.db.rpc.TransactionalMutateRequestOrBuilder getTransactionalMutateRequestOrBuilder() {
      if ((requestCase_ == 4) && (transactionalMutateRequestBuilder_ != null)) {
        return transactionalMutateRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 4) {
          return (com.scalar.db.rpc.TransactionalMutateRequest) request_;
        }
        return com.scalar.db.rpc.TransactionalMutateRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.TransactionalMutateRequest transactional_mutate_request = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.TransactionalMutateRequest, com.scalar.db.rpc.TransactionalMutateRequest.Builder, com.scalar.db.rpc.TransactionalMutateRequestOrBuilder> 
        getTransactionalMutateRequestFieldBuilder() {
      if (transactionalMutateRequestBuilder_ == null) {
        if (!(requestCase_ == 4)) {
          request_ = com.scalar.db.rpc.TransactionalMutateRequest.getDefaultInstance();
        }
        transactionalMutateRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.scalar.db.rpc.TransactionalMutateRequest, com.scalar.db.rpc.TransactionalMutateRequest.Builder, com.scalar.db.rpc.TransactionalMutateRequestOrBuilder>(
                (com.scalar.db.rpc.TransactionalMutateRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 4;
      onChanged();;
      return transactionalMutateRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.CommitRequest, com.scalar.db.rpc.CommitRequest.Builder, com.scalar.db.rpc.CommitRequestOrBuilder> commitRequestBuilder_;
    /**
     * <code>.rpc.CommitRequest commit_request = 5;</code>
     * @return Whether the commitRequest field is set.
     */
    @java.lang.Override
    public boolean hasCommitRequest() {
      return requestCase_ == 5;
    }
    /**
     * <code>.rpc.CommitRequest commit_request = 5;</code>
     * @return The commitRequest.
     */
    @java.lang.Override
    public com.scalar.db.rpc.CommitRequest getCommitRequest() {
      if (commitRequestBuilder_ == null) {
        if (requestCase_ == 5) {
          return (com.scalar.db.rpc.CommitRequest) request_;
        }
        return com.scalar.db.rpc.CommitRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 5) {
          return commitRequestBuilder_.getMessage();
        }
        return com.scalar.db.rpc.CommitRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.CommitRequest commit_request = 5;</code>
     */
    public Builder setCommitRequest(com.scalar.db.rpc.CommitRequest value) {
      if (commitRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        commitRequestBuilder_.setMessage(value);
      }
      requestCase_ = 5;
      return this;
    }
    /**
     * <code>.rpc.CommitRequest commit_request = 5;</code>
     */
    public Builder setCommitRequest(
        com.scalar.db.rpc.CommitRequest.Builder builderForValue) {
      if (commitRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        commitRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 5;
      return this;
    }
    /**
     * <code>.rpc.CommitRequest commit_request = 5;</code>
     */
    public Builder mergeCommitRequest(com.scalar.db.rpc.CommitRequest value) {
      if (commitRequestBuilder_ == null) {
        if (requestCase_ == 5 &&
            request_ != com.scalar.db.rpc.CommitRequest.getDefaultInstance()) {
          request_ = com.scalar.db.rpc.CommitRequest.newBuilder((com.scalar.db.rpc.CommitRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 5) {
          commitRequestBuilder_.mergeFrom(value);
        }
        commitRequestBuilder_.setMessage(value);
      }
      requestCase_ = 5;
      return this;
    }
    /**
     * <code>.rpc.CommitRequest commit_request = 5;</code>
     */
    public Builder clearCommitRequest() {
      if (commitRequestBuilder_ == null) {
        if (requestCase_ == 5) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 5) {
          requestCase_ = 0;
          request_ = null;
        }
        commitRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.rpc.CommitRequest commit_request = 5;</code>
     */
    public com.scalar.db.rpc.CommitRequest.Builder getCommitRequestBuilder() {
      return getCommitRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.rpc.CommitRequest commit_request = 5;</code>
     */
    @java.lang.Override
    public com.scalar.db.rpc.CommitRequestOrBuilder getCommitRequestOrBuilder() {
      if ((requestCase_ == 5) && (commitRequestBuilder_ != null)) {
        return commitRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 5) {
          return (com.scalar.db.rpc.CommitRequest) request_;
        }
        return com.scalar.db.rpc.CommitRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.CommitRequest commit_request = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.CommitRequest, com.scalar.db.rpc.CommitRequest.Builder, com.scalar.db.rpc.CommitRequestOrBuilder> 
        getCommitRequestFieldBuilder() {
      if (commitRequestBuilder_ == null) {
        if (!(requestCase_ == 5)) {
          request_ = com.scalar.db.rpc.CommitRequest.getDefaultInstance();
        }
        commitRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.scalar.db.rpc.CommitRequest, com.scalar.db.rpc.CommitRequest.Builder, com.scalar.db.rpc.CommitRequestOrBuilder>(
                (com.scalar.db.rpc.CommitRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 5;
      onChanged();;
      return commitRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.AbortRequest, com.scalar.db.rpc.AbortRequest.Builder, com.scalar.db.rpc.AbortRequestOrBuilder> abortRequestBuilder_;
    /**
     * <code>.rpc.AbortRequest abort_request = 6;</code>
     * @return Whether the abortRequest field is set.
     */
    @java.lang.Override
    public boolean hasAbortRequest() {
      return requestCase_ == 6;
    }
    /**
     * <code>.rpc.AbortRequest abort_request = 6;</code>
     * @return The abortRequest.
     */
    @java.lang.Override
    public com.scalar.db.rpc.AbortRequest getAbortRequest() {
      if (abortRequestBuilder_ == null) {
        if (requestCase_ == 6) {
          return (com.scalar.db.rpc.AbortRequest) request_;
        }
        return com.scalar.db.rpc.AbortRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 6) {
          return abortRequestBuilder_.getMessage();
        }
        return com.scalar.db.rpc.AbortRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.AbortRequest abort_request = 6;</code>
     */
    public Builder setAbortRequest(com.scalar.db.rpc.AbortRequest value) {
      if (abortRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        abortRequestBuilder_.setMessage(value);
      }
      requestCase_ = 6;
      return this;
    }
    /**
     * <code>.rpc.AbortRequest abort_request = 6;</code>
     */
    public Builder setAbortRequest(
        com.scalar.db.rpc.AbortRequest.Builder builderForValue) {
      if (abortRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        abortRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 6;
      return this;
    }
    /**
     * <code>.rpc.AbortRequest abort_request = 6;</code>
     */
    public Builder mergeAbortRequest(com.scalar.db.rpc.AbortRequest value) {
      if (abortRequestBuilder_ == null) {
        if (requestCase_ == 6 &&
            request_ != com.scalar.db.rpc.AbortRequest.getDefaultInstance()) {
          request_ = com.scalar.db.rpc.AbortRequest.newBuilder((com.scalar.db.rpc.AbortRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 6) {
          abortRequestBuilder_.mergeFrom(value);
        }
        abortRequestBuilder_.setMessage(value);
      }
      requestCase_ = 6;
      return this;
    }
    /**
     * <code>.rpc.AbortRequest abort_request = 6;</code>
     */
    public Builder clearAbortRequest() {
      if (abortRequestBuilder_ == null) {
        if (requestCase_ == 6) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 6) {
          requestCase_ = 0;
          request_ = null;
        }
        abortRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.rpc.AbortRequest abort_request = 6;</code>
     */
    public com.scalar.db.rpc.AbortRequest.Builder getAbortRequestBuilder() {
      return getAbortRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.rpc.AbortRequest abort_request = 6;</code>
     */
    @java.lang.Override
    public com.scalar.db.rpc.AbortRequestOrBuilder getAbortRequestOrBuilder() {
      if ((requestCase_ == 6) && (abortRequestBuilder_ != null)) {
        return abortRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 6) {
          return (com.scalar.db.rpc.AbortRequest) request_;
        }
        return com.scalar.db.rpc.AbortRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.rpc.AbortRequest abort_request = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.db.rpc.AbortRequest, com.scalar.db.rpc.AbortRequest.Builder, com.scalar.db.rpc.AbortRequestOrBuilder> 
        getAbortRequestFieldBuilder() {
      if (abortRequestBuilder_ == null) {
        if (!(requestCase_ == 6)) {
          request_ = com.scalar.db.rpc.AbortRequest.getDefaultInstance();
        }
        abortRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.scalar.db.rpc.AbortRequest, com.scalar.db.rpc.AbortRequest.Builder, com.scalar.db.rpc.AbortRequestOrBuilder>(
                (com.scalar.db.rpc.AbortRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 6;
      onChanged();;
      return abortRequestBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.TransactionRequest)
  }

  // @@protoc_insertion_point(class_scope:rpc.TransactionRequest)
  private static final com.scalar.db.rpc.TransactionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scalar.db.rpc.TransactionRequest();
  }

  public static com.scalar.db.rpc.TransactionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransactionRequest>
      PARSER = new com.google.protobuf.AbstractParser<TransactionRequest>() {
    @java.lang.Override
    public TransactionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TransactionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransactionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransactionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scalar.db.rpc.TransactionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

