// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalardb.proto

// Protobuf Java Version: 3.25.5
package com.scalar.db.rpc;

@java.lang.Deprecated public interface ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.Value)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bool boolean_value = 2;</code>
   * @return Whether the booleanValue field is set.
   */
  boolean hasBooleanValue();
  /**
   * <code>bool boolean_value = 2;</code>
   * @return The booleanValue.
   */
  boolean getBooleanValue();

  /**
   * <code>int32 int_value = 3;</code>
   * @return Whether the intValue field is set.
   */
  boolean hasIntValue();
  /**
   * <code>int32 int_value = 3;</code>
   * @return The intValue.
   */
  int getIntValue();

  /**
   * <code>int64 bigint_value = 4;</code>
   * @return Whether the bigintValue field is set.
   */
  boolean hasBigintValue();
  /**
   * <code>int64 bigint_value = 4;</code>
   * @return The bigintValue.
   */
  long getBigintValue();

  /**
   * <code>float float_value = 5;</code>
   * @return Whether the floatValue field is set.
   */
  boolean hasFloatValue();
  /**
   * <code>float float_value = 5;</code>
   * @return The floatValue.
   */
  float getFloatValue();

  /**
   * <code>double double_value = 6;</code>
   * @return Whether the doubleValue field is set.
   */
  boolean hasDoubleValue();
  /**
   * <code>double double_value = 6;</code>
   * @return The doubleValue.
   */
  double getDoubleValue();

  /**
   * <code>.rpc.Value.TextValue text_value = 7;</code>
   * @return Whether the textValue field is set.
   */
  boolean hasTextValue();
  /**
   * <code>.rpc.Value.TextValue text_value = 7;</code>
   * @return The textValue.
   */
  com.scalar.db.rpc.Value.TextValue getTextValue();
  /**
   * <code>.rpc.Value.TextValue text_value = 7;</code>
   */
  com.scalar.db.rpc.Value.TextValueOrBuilder getTextValueOrBuilder();

  /**
   * <code>.rpc.Value.BlobValue blob_value = 8;</code>
   * @return Whether the blobValue field is set.
   */
  boolean hasBlobValue();
  /**
   * <code>.rpc.Value.BlobValue blob_value = 8;</code>
   * @return The blobValue.
   */
  com.scalar.db.rpc.Value.BlobValue getBlobValue();
  /**
   * <code>.rpc.Value.BlobValue blob_value = 8;</code>
   */
  com.scalar.db.rpc.Value.BlobValueOrBuilder getBlobValueOrBuilder();

  com.scalar.db.rpc.Value.ValueCase getValueCase();
}
