scalar.db.storage=jdbc
scalar.db.contact_points=jdbc:postgresql://localhost:15440/sdb
scalar.db.username=postgres
scalar.db.password=
scalar.db.transaction_manager=consensus-commit
scalar.db.cross_partition_scan.enabled=true
scalar.db.cross_partition_scan.filtering.enabled=true
scalar.db.cross_partition_scan.ordering.enabled=true
