#!/usr/bin/env bash

set -e -o pipefail; [[ -n "$DEBUG" ]] && set -x

if [[ $# -ne 3 ]]; then
    echo "usage: $0 repo_owner repo_name pull_request_id"
    exit 1
fi

repo_owner=$1
repo_name=$2
pull_request_id=$3

# Get GitHub projects associated with the merged PR and extract full versions (e.g. "3.7.1")
versions_json=$(gh api graphql -F owner=$repo_owner -F repoName=$repo_name -F pullRequestId=$pull_request_id -f query='
  query($owner: String!, $repoName: String!, $pullRequestId: Int!) {
    repository(owner: $owner, name: $repoName) {
      pullRequest(number: $pullRequestId) {
        projectsV2(first: 100) {
          nodes {
            title
          }
        }
      }
    }
  }
')

echo $versions_json | jq -r '.data.repository.pullRequest.projectsV2.nodes[].title' | sed -n 's/^ScalarDB \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p'

