# Define all integration tests to be run in the CI.

# Each test follows the following format:
# test_category:
#   - label: a unique label for the test
#     display_name: a human-readable name
#     runner: (optional) the image name of a hosted Github action runner. The default is "ubuntu-latest".
#     versions: (optional) an array of database versions to test. If present, a matrix entry for each version will be added and the placeholder %VERSION% will be substituted.
#     disable_group_commit: (optional) if true, the test will not be run with group commit enabled. By default, a matrix entry with group commit enabled and another one with group commit disabled will be added.
#     setup: a script to set up the database. In Linux runners, the script will be run in bash shell. For Windows runners, it will be run in powershell.
#     db_healthcheck: (optional) a bash script that succeed if the database is ready. The script will be run repeatedly with a delay until it succeeds with a 10 minutes timeout. If not provided, it is assumed the database is ready before the run script is executed.
#     create_test_user: (optional) a bash script to create a non-admin test user with necessary permissions to run the integration test. If not provided, it is assumed that the default user has sufficient permissions.
#     run: a script to run the test. In Linux runners, the script will be run in bash shell. For Windows runners, it will be run in powershell.

dynamo:
  - label: dynamo_nb_worker_%VERSION%
    display_name: DynamoDB Local with %VERSION% workers
    setup: docker run -d --name dynamodb -p 8000:8000 amazon/dynamodb-local
    # Permissions cannot be tested on DynamoDB local
    create_test_user: # Do nothing
    versions:
      - 2
      - 4
      - 6
      - 8
    run: ./gradlew integrationTestDynamo -Dscalardb.max_parallel_fork=%VERSION%

jdbc:
  - label: postgresql_17_nb_worker_%VERSION%
    display_name: PostgreSQL 17 with %VERSION% workers
    setup: docker run -d --name postgresql -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:17-alpine
    versions:
      - 2
      - 4
      - 6
      - 8
    db_healthcheck: docker exec postgresql psql -U postgres -c "SELECT 1;" > /dev/null 2>&1
    create_test_user: |
      docker exec postgresql psql -U postgres -c "
        CREATE USER test WITH PASSWORD 'test';
        GRANT CREATE ON DATABASE postgres TO test;"
    run: ./gradlew integrationTestJdbc -Dscalardb.jdbc.url=jdbc:postgresql://localhost:5432/postgres -Dscalardb.jdbc.username=test -Dscalardb.jdbc.password=test -Dscalardb.max_parallel_fork=%VERSION%




