package com.scalar.db.common;

import com.scalar.db.api.BranchTransaction;
import com.scalar.db.api.CrudOperable;
import com.scalar.db.api.Delete;
import com.scalar.db.api.DistributedTransaction;
import com.scalar.db.api.Get;
import com.scalar.db.api.GlobalTransaction;
import com.scalar.db.api.GlobalTransactionManager;
import com.scalar.db.api.Insert;
import com.scalar.db.api.Isolation;
import com.scalar.db.api.Mutation;
import com.scalar.db.api.Operation;
import com.scalar.db.api.Put;
import com.scalar.db.api.Result;
import com.scalar.db.api.Scan;
import com.scalar.db.api.Selection;
import com.scalar.db.api.SerializableStrategy;
import com.scalar.db.api.TransactionCrudOperable;
import com.scalar.db.api.TransactionManagerCrudOperable;
import com.scalar.db.api.TransactionState;
import com.scalar.db.api.Update;
import com.scalar.db.api.Upsert;
import com.scalar.db.config.DatabaseConfig;
import com.scalar.db.exception.transaction.CommitConflictException;
import com.scalar.db.exception.transaction.CrudConflictException;
import com.scalar.db.exception.transaction.CrudException;
import com.scalar.db.exception.transaction.RollbackException;
import com.scalar.db.exception.transaction.TransactionException;
import com.scalar.db.exception.transaction.TransactionNotFoundException;
import com.scalar.db.exception.transaction.UnknownTransactionStatusException;
import com.scalar.db.io.Key;
import com.scalar.db.util.ThrowableFunction;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicBoolean;
import javax.annotation.Nullable;

/**
 * Test-only adapter that drives the {@link com.scalar.db.api.GlobalTransactionManager} / {@link
 * GlobalTransaction} / {@link BranchTransaction} layer behind the {@link
 * com.scalar.db.api.DistributedTransactionManager} API.
 *
 * <p>Each {@code begin} allocates a global transaction and a branch, and returns a {@link
 * GlobalTransactionBackedDistributedTransaction} that internalizes the full two-phase commit behind
 * the single-phase {@code commit()}. This lets the existing {@code DistributedTransaction}
 * integration-test corpus run against the new Global/Branch layer. It lives in the integration-test
 * module and is not intended for production use.
 *
 * <p>A {@link GlobalTransactionManager} is injected (for the consensus-commit route, the {@link
 * com.scalar.db.common.TwoPhaseCommitBackedGlobalTransactionManager} built from a coordinator and a
 * participant).
 *
 * <p>Limitations, since this is only a test adapter over the Global/Branch layer:
 *
 * <ul>
 *   <li>The caller-supplied {@code txId} passed to {@code begin} / {@code beginReadOnly} is not
 *       honored: the global transaction ID is always generated by the coordinator. Tests that
 *       depend on a specific begin ID are unsupported.
 *   <li>{@code join} and {@code resume} are unsupported and throw {@link
 *       UnsupportedOperationException} (a joined/resumed handle would need to reach an existing
 *       global transaction, which the Global/Branch layer does not expose).
 *   <li>The by-ID Coordinator-table operations {@link #getState(String)}, {@link #rollback(String)}
 *       (and {@code abort(String)}, which delegates to it), {@link #finishTransaction(String)}, and
 *       {@code recoverRecord} are unsupported and throw {@link UnsupportedOperationException}.
 *   <li>The deprecated {@code start(...)} overloads ignore the per-transaction isolation /
 *       serializable strategy they carry; isolation comes from configuration instead.
 * </ul>
 */
public class GlobalTransactionBackedDistributedTransactionManager
    extends AbstractDistributedTransactionManager {

  private final GlobalTransactionManager globalTransactionManager;

  /**
   * Creates a manager over the given {@link GlobalTransactionManager}.
   *
   * @param config a database config
   * @param globalTransactionManager the global transaction manager to drive
   */
  @SuppressFBWarnings("EI_EXPOSE_REP2")
  public GlobalTransactionBackedDistributedTransactionManager(
      DatabaseConfig config, GlobalTransactionManager globalTransactionManager) {
    super(config);
    this.globalTransactionManager = globalTransactionManager;
  }

  @Override
  public DistributedTransaction begin(String txId, Map<String, String> attributes)
      throws TransactionException {
    return beginInternal(false, attributes);
  }

  @Override
  public DistributedTransaction beginReadOnly(String txId, Map<String, String> attributes)
      throws TransactionException {
    return beginInternal(true, attributes);
  }

  private DistributedTransaction beginInternal(boolean readOnly, Map<String, String> attributes)
      throws TransactionException {
    // The caller-supplied txId is not honored; the coordinator generates the global transaction ID.
    GlobalTransaction global =
        readOnly
            ? globalTransactionManager.beginGlobalReadOnly(attributes)
            : globalTransactionManager.beginGlobal(attributes);
    BranchTransaction branch;
    try {
      branch = globalTransactionManager.beginBranch(global.getId(), attributes);
    } catch (TransactionException e) {
      // A failed branch begin would leave the just-begun global transaction orphaned; roll it back
      // so begin-then-branch is atomic from the caller's perspective. Best-effort: an abandoned
      // global transaction is idle-reaped anyway if this rollback also fails.
      try {
        global.rollback();
      } catch (RollbackException ignored) {
        // Ignore; the context will be reclaimed by idle expiry.
      }
      throw e;
    }
    DistributedTransaction transaction = createTransaction(global, branch);
    getNamespace().ifPresent(transaction::withNamespace);
    getTable().ifPresent(transaction::withTable);
    return transaction;
  }

  /**
   * Creates the {@link DistributedTransaction} instance returned by {@link #begin} and {@link
   * #beginReadOnly}. This is a template method: subclasses can override it to customize the
   * transaction instance (for example, to wrap it in a decorator).
   *
   * @param globalTransaction the global transaction driving commit/rollback
   * @param branchTransaction the branch handling CRUD
   * @return the transaction instance
   */
  protected DistributedTransaction createTransaction(
      GlobalTransaction globalTransaction, BranchTransaction branchTransaction) {
    return new GlobalTransactionBackedDistributedTransaction(globalTransaction, branchTransaction);
  }

  // The deprecated start(...) overloads carry per-transaction isolation / serializable strategy,
  // which this path does not honor (isolation comes from configuration). Delegate to begin.

  /** @deprecated As of release 2.4.0. Will be removed in release 4.0.0 */
  @Deprecated
  @Override
  public DistributedTransaction start(Isolation isolation) throws TransactionException {
    return begin();
  }

  /** @deprecated As of release 2.4.0. Will be removed in release 4.0.0 */
  @Deprecated
  @Override
  public DistributedTransaction start(String txId, Isolation isolation)
      throws TransactionException {
    return begin(txId);
  }

  /** @deprecated As of release 2.4.0. Will be removed in release 4.0.0 */
  @Deprecated
  @Override
  public DistributedTransaction start(Isolation isolation, SerializableStrategy strategy)
      throws TransactionException {
    return begin();
  }

  /** @deprecated As of release 2.4.0. Will be removed in release 4.0.0 */
  @Deprecated
  @Override
  public DistributedTransaction start(SerializableStrategy strategy) throws TransactionException {
    return begin();
  }

  /** @deprecated As of release 2.4.0. Will be removed in release 4.0.0 */
  @Deprecated
  @Override
  public DistributedTransaction start(String txId, SerializableStrategy strategy)
      throws TransactionException {
    return begin(txId);
  }

  /** @deprecated As of release 2.4.0. Will be removed in release 4.0.0 */
  @Deprecated
  @Override
  public DistributedTransaction start(
      String txId, Isolation isolation, SerializableStrategy strategy) throws TransactionException {
    return begin(txId);
  }

  // ---- TransactionManagerCrudOperable: one-shot CRUD (begin -> op -> commit) ----

  @Override
  public Optional<Result> get(Get get) throws CrudException, UnknownTransactionStatusException {
    return executeTransaction(t -> t.get(copyAndSetTargetToIfNot(get)), true, get.getAttributes());
  }

  @Override
  public List<Result> scan(Scan scan) throws CrudException, UnknownTransactionStatusException {
    return executeTransaction(
        t -> t.scan(copyAndSetTargetToIfNot(scan)), true, scan.getAttributes());
  }

  @Override
  public TransactionManagerCrudOperable.Scanner getScanner(Scan scan) throws CrudException {
    DistributedTransaction transaction = beginOneOperation(true, scan.getAttributes());
    TransactionCrudOperable.Scanner scanner;
    try {
      scanner = transaction.getScanner(copyAndSetTargetToIfNot(scan));
    } catch (CrudException e) {
      rollbackTransaction(transaction);
      throw e;
    }
    return new AbstractTransactionManagerCrudOperableScanner() {
      private final AtomicBoolean closed = new AtomicBoolean();

      @Override
      public Optional<Result> one() throws CrudException {
        try {
          return scanner.one();
        } catch (CrudException e) {
          closeScannerAndRollback(e);
          throw e;
        }
      }

      @Override
      public List<Result> all() throws CrudException {
        try {
          return scanner.all();
        } catch (CrudException e) {
          closeScannerAndRollback(e);
          throw e;
        }
      }

      @Override
      public void close() throws CrudException, UnknownTransactionStatusException {
        if (!closed.compareAndSet(false, true)) {
          return;
        }
        try {
          scanner.close();
        } catch (CrudException e) {
          rollbackTransaction(transaction);
          throw e;
        }
        try {
          transaction.commit();
        } catch (CommitConflictException e) {
          rollbackTransaction(transaction);
          throw new CrudConflictException(e.getMessage(), e, e.getTransactionId().orElse(null));
        } catch (UnknownTransactionStatusException e) {
          throw e;
        } catch (TransactionException e) {
          rollbackTransaction(transaction);
          throw new CrudException(e.getMessage(), e, e.getTransactionId().orElse(null));
        }
      }

      private void closeScannerAndRollback(CrudException cause) {
        closed.set(true);
        try {
          scanner.close();
        } catch (CrudException ex) {
          cause.addSuppressed(ex);
        }
        rollbackTransaction(transaction);
      }
    };
  }

  /** @deprecated As of release 3.13.0. Will be removed in release 4.0.0 */
  @Deprecated
  @Override
  public void put(Put put) throws CrudException, UnknownTransactionStatusException {
    executeTransaction(
        t -> {
          t.put(copyAndSetTargetToIfNot(put));
          return null;
        },
        false,
        put.getAttributes());
  }

  /** @deprecated As of release 3.13.0. Will be removed in release 4.0.0 */
  @Deprecated
  @Override
  public void put(List<Put> puts) throws CrudException, UnknownTransactionStatusException {
    executeTransaction(
        t -> {
          t.put(copyAndSetTargetToIfNot(puts));
          return null;
        },
        false,
        puts.isEmpty() ? Collections.emptyMap() : puts.get(0).getAttributes());
  }

  @Override
  public void insert(Insert insert) throws CrudException, UnknownTransactionStatusException {
    executeTransaction(
        t -> {
          t.insert(copyAndSetTargetToIfNot(insert));
          return null;
        },
        false,
        insert.getAttributes());
  }

  @Override
  public void upsert(Upsert upsert) throws CrudException, UnknownTransactionStatusException {
    executeTransaction(
        t -> {
          t.upsert(copyAndSetTargetToIfNot(upsert));
          return null;
        },
        false,
        upsert.getAttributes());
  }

  @Override
  public void update(Update update) throws CrudException, UnknownTransactionStatusException {
    executeTransaction(
        t -> {
          t.update(copyAndSetTargetToIfNot(update));
          return null;
        },
        false,
        update.getAttributes());
  }

  @Override
  public void delete(Delete delete) throws CrudException, UnknownTransactionStatusException {
    executeTransaction(
        t -> {
          t.delete(copyAndSetTargetToIfNot(delete));
          return null;
        },
        false,
        delete.getAttributes());
  }

  /** @deprecated As of release 3.13.0. Will be removed in release 4.0.0 */
  @Deprecated
  @Override
  public void delete(List<Delete> deletes) throws CrudException, UnknownTransactionStatusException {
    executeTransaction(
        t -> {
          t.delete(copyAndSetTargetToIfNot(deletes));
          return null;
        },
        false,
        deletes.isEmpty() ? Collections.emptyMap() : deletes.get(0).getAttributes());
  }

  @Override
  public void mutate(List<? extends Mutation> mutations)
      throws CrudException, UnknownTransactionStatusException {
    executeTransaction(
        t -> {
          t.mutate(copyAndSetTargetToIfNot(mutations));
          return null;
        },
        false,
        mutations.isEmpty() ? Collections.emptyMap() : mutations.get(0).getAttributes());
  }

  @Override
  public List<CrudOperable.BatchResult> batch(List<? extends Operation> operations)
      throws CrudException, UnknownTransactionStatusException {
    boolean readOnly = operations.stream().allMatch(o -> o instanceof Selection);
    return executeTransaction(
        t -> t.batch(copyAndSetTargetToIfNot(operations)),
        readOnly,
        operations.isEmpty() ? Collections.emptyMap() : operations.get(0).getAttributes());
  }

  private <R> R executeTransaction(
      ThrowableFunction<DistributedTransaction, R, TransactionException> operation,
      boolean readOnly,
      Map<String, String> attributes)
      throws CrudException, UnknownTransactionStatusException {
    DistributedTransaction transaction = beginOneOperation(readOnly, attributes);
    try {
      R result = operation.apply(transaction);
      transaction.commit();
      return result;
    } catch (CrudException e) {
      rollbackTransaction(transaction);
      throw e;
    } catch (CommitConflictException e) {
      rollbackTransaction(transaction);
      throw new CrudConflictException(e.getMessage(), e, e.getTransactionId().orElse(null));
    } catch (UnknownTransactionStatusException e) {
      throw e;
    } catch (TransactionException e) {
      rollbackTransaction(transaction);
      throw new CrudException(e.getMessage(), e, e.getTransactionId().orElse(null));
    }
  }

  private DistributedTransaction beginOneOperation(boolean readOnly, Map<String, String> attributes)
      throws CrudException {
    try {
      return readOnly ? beginReadOnly(attributes) : begin(attributes);
    } catch (TransactionNotFoundException e) {
      // A transient begin failure surfaces as a retriable CRUD conflict.
      throw new CrudConflictException(e.getMessage(), e, e.getTransactionId().orElse(null));
    } catch (TransactionException e) {
      throw new CrudException(e.getMessage(), e, e.getTransactionId().orElse(null));
    }
  }

  private void rollbackTransaction(DistributedTransaction transaction) {
    try {
      transaction.rollback();
    } catch (RollbackException ignored) {
      // Best-effort rollback; the original error is the one that matters.
    }
  }

  @Override
  public TransactionState getState(String txId) {
    throw new UnsupportedOperationException(
        "getState is not supported by the global-transaction-backed transaction manager");
  }

  @Override
  public boolean finishTransaction(String txId) {
    throw new UnsupportedOperationException(
        "finishTransaction is not supported by the global-transaction-backed transaction manager");
  }

  @Override
  public boolean recoverRecord(
      String namespace, String table, Key partitionKey, @Nullable Key clusteringKey) {
    throw new UnsupportedOperationException(
        "recoverRecord is not supported by the global-transaction-backed transaction manager");
  }

  @Override
  public TransactionState rollback(String txId) {
    throw new UnsupportedOperationException(
        "rollback/abort by transaction ID is not supported by the global-transaction-backed"
            + " transaction manager");
  }

  @Override
  public void close() {
    globalTransactionManager.close();
  }
}
