name: CI
run-name: "${{ github.event_name == 'workflow_dispatch' && format('Dispatch : Run CI with JDK {0} ({1})', inputs.INT_TEST_JAVA_RUNTIME_VERSION, inputs.INT_TEST_JAVA_RUNTIME_VENDOR) || '' }}"

on:
#  # When triggered by a pull request, basic integration tests will run in addition to the tests related
#  # to the file changes. JDK 8 (Temurin) will be used at runtime.
  # TODO enable again
#  pull_request:

  # When triggered by a dispatch, selected tests will run with the given integration tests JDK runtime.
  workflow_dispatch:
    inputs:
      ALL:
        description: Run all integration tests
        type: boolean
        default: true
      BASIC:
        description: Run basic integration tests
        type: boolean
        default: false
      BLOB_STORAGE:
        description: Run Blob storage integration tests
        type: boolean
        default: false
      CASSANDRA:
        description: Run Cassandra integration tests
        type: boolean
        default: false
      COSMOS:
        description: Run Cosmos DB integration tests
        type: boolean
        default: false
      DYNAMO:
        description: Run DynamoDB integration tests
        type: boolean
        default: false
      JDBC:
        description: Run JDBC integration tests
        type: boolean
        default: false
      MULTI_STORAGE:
        description: Run multi-storage integration tests
        type: boolean
        default: false
      INT_TEST_JAVA_RUNTIME_VERSION:
        description: JDK version used to run the integration test
        type: choice
        default: '8'
        options:
          - '8'
          - '11'
          - '17'
          - '21'
      INT_TEST_JAVA_RUNTIME_VENDOR:
        description: Vendor of the JDK used to run the integration test
        type: choice
        default: 'temurin'
        options:
          - 'corretto'
          - 'microsoft'
          - 'oracle'
          - 'temurin'
      INTEGRATION_TEST_ONLY:
        description: Run only integration tests
        type: boolean
        default: false

  # When triggered by another action, all tests will run with the given integration test JDK runtime.
  workflow_call:
    inputs:
      ALL:
        description: Run all integration tests
        type: boolean
        default: true
      INT_TEST_JAVA_RUNTIME_VERSION:
        description: JDK version used to run the integration test
        type: string
        required: true
      INT_TEST_JAVA_RUNTIME_VENDOR:
        description: Vendor of the JDK used to run the integration test
        type: string
        required: true
      INTEGRATION_TEST_ONLY:
        description: Run only integration tests
        type: boolean
        default: false
env:
  TERM: dumb
  ARTIFACT_SUFFIX: ${{ inputs.INT_TEST_JAVA_RUNTIME_VERSION || '8' }}_${{ inputs.INT_TEST_JAVA_RUNTIME_VENDOR || 'temurin' }}

jobs:
  check:
    name: Gradle check
    runs-on: ubuntu-latest
    if: ${{ !inputs.INTEGRATION_TEST_ONLY }}

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Execute Gradle 'check' task
        # TODO Enable again
        # run: ./gradlew check -x test buildSrc:check
        run: ./gradlew check buildSrc:check

      - name: Save Gradle test reports
        if: always()
        run: |
          mkdir -p /tmp/gradle_test_reports/core
          mkdir -p /tmp/gradle_test_reports/schema-loader
          mkdir -p /tmp/gradle_test_reports/data-loader/core
          mkdir -p /tmp/gradle_test_reports/data-loader/cli
          cp -a core/build/reports/tests/test /tmp/gradle_test_reports/core/
          cp -a schema-loader/build/reports/tests/test /tmp/gradle_test_reports/schema-loader/
          cp -a data-loader/core/build/reports/tests/test /tmp/gradle_test_reports/data-loader/core/
          cp -a data-loader/cli/build/reports/tests/test /tmp/gradle_test_reports/data-loader/cli/

      - name: Upload Gradle test reports
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: gradle_check_reports
          path: /tmp/gradle_test_reports

      - name: Save SpotBugs reports
        if: always()
        run: |
          mkdir -p /tmp/gradle_spotbugs_reports/core
          mkdir -p /tmp/gradle_spotbugs_reports/schema-loader
          mkdir -p /tmp/gradle_spotbugs_reports/integration-test
          mkdir -p /tmp/gradle_spotbugs_reports/data-loader/core
          mkdir -p /tmp/gradle_spotbugs_reports/data-loader/cli
          cp -a core/build/reports/spotbugs /tmp/gradle_spotbugs_reports/core/
          cp -a schema-loader/build/reports/spotbugs /tmp/gradle_spotbugs_reports/schema-loader/
          cp -a integration-test/build/reports/spotbugs /tmp/gradle_spotbugs_reports/integration-test/
          cp -a data-loader/core/build/reports/spotbugs /tmp/gradle_spotbugs_reports/data-loader/core/
          cp -a data-loader/cli/build/reports/spotbugs /tmp/gradle_spotbugs_reports/data-loader/cli/

      - name: Upload Spotbugs reports
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: gradle_spotbugs_reports_${{ env.ARTIFACT_SUFFIX }}
          path: /tmp/gradle_spotbugs_reports

  dockerfile-lint:
    name: Lint dockerfiles
    runs-on: ubuntu-latest
    if: ${{ !inputs.INTEGRATION_TEST_ONLY }}

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Dockerfile Lint for ScalarDB Schema Loader
        run: ./gradlew schema-loader:dockerfileLint

      - name: Dockerfile Lint for ScalarDB Data Loader CLI
        run: ./gradlew data-loader:cli:dockerfileLint

  # Set up which integration test categories to run
  integration-test-jobs-planner:
    name: Planner for integration test jobs
    runs-on: ubuntu-latest
    env:
      ALL: ${{ inputs.ALL }}
      BASIC: ${{ inputs.BASIC }}
      BLOB_STORAGE: ${{ inputs.BLOB_STORAGE }}
      CASSANDRA: ${{ inputs.CASSANDRA }}
      COSMOS: ${{ inputs.COSMOS }}
      DYNAMO: ${{ inputs.DYNAMO }}
      JDBC: ${{ inputs.JDBC }}
      MULTI_STORAGE: ${{ inputs.MULTI_STORAGE }}
      TRIGGERED_BY_WF_DISPATCH: ${{ github.event_name == 'workflow_dispatch' }}
    outputs:
      test_matrix: ${{ steps.generate-matrix-for-wf-dispatch.outputs.matrix || steps.generate-matrix-by-changes.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Install Groovy
        run: |
          curl -s "https://get.sdkman.io?ci=true" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install groovy
          echo "$HOME/.sdkman/candidates/groovy/current/bin" >> $GITHUB_PATH

      - name: Validate workflow dispatch inputs
        if: env.TRIGGERED_BY_WF_DISPATCH
        run: |
          if [ "$ALL" != "true" ]; then
            # Check if at least one specific test category is enabled
            if [ "$BASIC" != "true" ] && \
               [ "$BLOB_STORAGE" != "true" ] && \
               [ "$CASSANDRA" != "true" ] && \
               [ "$COSMOS" != "true" ] && \
               [ "$DYNAMO" != "true" ] && \
               [ "$JDBC" != "true" ] && \
               [ "$MULTI_STORAGE" != "true" ]; then
              echo "Error: When the ALL workflow input is false, at least one specific test category must be enabled."
              echo "Please enable at least one of: BASIC, BLOB_STORAGE, CASSANDRA, COSMOS, DYNAMO, JDBC, MULTI_STORAGE."
              exit 1
            fi
          fi

      - name: Generate the node integration tests matrix when invoked by workflow_dispatch
        id: generate-matrix-for-wf-dispatch
        if: env.TRIGGERED_BY_WF_DISPATCH
        run: |
          MATRIX_JSON=$(groovy ci/integration-test/generate-test-matrix-for-wf-dispatch.groovy)
          echo "matrix=${MATRIX_JSON}" >> $GITHUB_OUTPUT

#      - name: Generate the Cluster node integration tests matrix based on file changes
#        id: generate-matrix-by-changes
#        if: ${{ !env.TRIGGERED_BY_WF_DISPATCH }}
#        env:
#          PR_BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
#        run: |
#          MATRIX_JSON=$(groovy ci/integration-test/generate-test-matrix-for-file-changes.groovy)
#          echo "matrix=${MATRIX_JSON}" >> $GITHUB_OUTPUT

      - name: Check which test categories will run
        id: check-test-categories
        run: |
          # Get the matrix JSON from either workflow dispatch or file changes
          MATRIX_JSON='${{ steps.generate-matrix-for-wf-dispatch.outputs.matrix || steps.generate-matrix-by-changes.outputs.matrix }}'
          
          echo Integration test matrix:
          echo "$MATRIX_JSON" | jq .

  integration-test:
    name: ${{ matrix.display_name }} integration test (${{ matrix.group_commit_enabled == true && 'with group commit' || 'default' }})
    needs:
      - integration-test-jobs-planner
    runs-on: ${{ matrix.runner == '' && 'ubuntu-latest' || matrix.runner }}
    env:
      INT_TEST_JAVA_RUNTIME_VERSION: ${{ inputs.INT_TEST_JAVA_RUNTIME_VERSION || '8' }}
      INT_TEST_JAVA_RUNTIME_VENDOR: ${{ inputs.INT_TEST_JAVA_RUNTIME_VENDOR || 'temurin' }}

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.integration-test-jobs-planner.outputs.test_matrix) }}

    steps:
      - uses: actions/checkout@v6

      - name: Set up the database
        run: ${{ matrix.setup_db }}

      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: temurin

      - name: Set up JDK ${{ inputs.INT_TEST_JAVA_RUNTIME_VERSION }} (${{ inputs.INT_TEST_JAVA_RUNTIME_VENDOR }}) to run integration test
        id: setup-int-test-jdk
        uses: actions/setup-java@v5
        # On Linux runner, skip if Oracle JDK is specified
        # On Windows runner, skip if Oracle JDK 8 or 11 is specified
        if: ${{ (runner.os == 'Linux' && inputs.INT_TEST_JAVA_RUNTIME_VENDOR != 'oracle') || (runner.os == 'Windows' && !(inputs.INT_TEST_JAVA_RUNTIME_VENDOR == 'oracle' && (inputs.INT_TEST_JAVA_RUNTIME_VERSION == '8' || inputs.INT_TEST_JAVA_RUNTIME_VERSION == '11')))  }}
        with:
          java-version: ${{ inputs.INT_TEST_JAVA_RUNTIME_VERSION }}
          distribution: ${{ inputs.INT_TEST_JAVA_RUNTIME_VENDOR }}

      - name: Set up JDK ${{ inputs.INT_TEST_JAVA_RUNTIME_VERSION }} (oracle) to run the integration test
        if: ${{ steps.setup-int-test-jdk.outcome == 'skipped' }}
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            # Linux runner, install Oracle JDK for any versions from Oracle Container Registry
            docker login container-registry.oracle.com -u ${{ secrets.OCR_USERNAME }} -p ${{ secrets.OCR_TOKEN }}
            container_id=$(docker create "container-registry.oracle.com/java/jdk:${{ inputs.INT_TEST_JAVA_RUNTIME_VERSION }}")
            docker cp -L "$container_id:/usr/java/default" /usr/lib/jvm/oracle-jdk && docker rm "$container_id"
          else
            # Windows runner, install Oracle JDK 8 or 11 from Scalar Container Registry
            docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.CR_PAT }}
            container_id=$(docker create "ghcr.io/scalar-labs/oracle/jdk:${{ env.INT_TEST_JAVA_RUNTIME_VERSION }}-windows")
            docker cp "${container_id}:oracle-jdk.exe" .
            docker rm "$container_id"
            echo "Install Oracle JDK"
            ./oracle-jdk.exe /s
            echo "Oracle JDK installation successful"
            if [[ "${{ env.INT_TEST_JAVA_RUNTIME_VERSION }}" == "8" ]]; then
              jdk_root_dir="jdk-1.8"
            else
              jdk_root_dir="jdk-11"
            fi
            echo "JAVA_HOME=C:\\Program Files\\Java\\${jdk_root_dir}" >> "$GITHUB_ENV"
          fi

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Run integration test
        id: execute-integration-test
        env:
          ORG_GRADLE_PROJECT_javaVersion: '8'
          ORG_GRADLE_PROJECT_javaVendor: 'temurin'
          ORG_GRADLE_PROJECT_integrationTestJavaRuntimeVersion: "${{ inputs.INT_TEST_JAVA_RUNTIME_VERSION }}"
          ORG_GRADLE_PROJECT_integrationTestJavaRuntimeVendor: "${{ inputs.INT_TEST_JAVA_RUNTIME_VENDOR }}"
          GROUP_COMMIT_OPTIONS: '"-Dscalardb.consensus_commit.coordinator.group_commit.enabled=true" "-Dscalardb.consensus_commit.coordinator.group_commit.old_group_abort_timeout_millis=15000" --tests "**.ConsensusCommit**"'
        run: ${{ matrix.test }} ${{ matrix.group_commit_enabled == 'true' && env.GROUP_COMMIT_OPTIONS || '' }}

      - name: Detect test report folder
        id: detect-report-folder
        if: always()
        shell: bash
        run: |
          report_dir="core/build/reports/tests"
          folder_name=$(ls -1 "$report_dir" | head -n 1)
          report_path=$report_dir/$folder_name
          if [ -d "$report_path" ]; then
            echo "report_path=$report_path" >> "$GITHUB_OUTPUT"
            echo "Detected test report folder: $report_path"
          else
            echo "Test report folder could not be found"
          fi

      - name: Upload Gradle test reports
        if: ${{ always() && steps.detect-report-folder.outputs.report_path != '' }}
        uses: actions/upload-artifact@v6
        with:
          name: ${{ steps.execute-integration-test.outcome == 'success' && 'success' || 'failure' }}_${{ matrix.label }}_${{ inputs.GROUP_COMMIT_ENABLED == 'true' && 'group_commit' || 'default' }}_test_${{ env.ARTIFACT_SUFFIX }}
          path: ${{ steps.detect-report-folder.outputs.report_path }}

  merge-artifacts:
    if: always()
    name: Merge all artifacts
    runs-on: ubuntu-latest
    needs:
      - check
      - dockerfile-lint
      - integration-test
    steps:
      - name: Merge all artifacts
        uses: actions/upload-artifact/merge@v5
        with:
          name: ci_report_${{ env.ARTIFACT_SUFFIX }}_run_#${{ github.run_attempt }}
          pattern: "*${{ env.ARTIFACT_SUFFIX }}"
          separate-directories: true
          delete-merged: true

