name: CI 2
run-name: "${{ github.event_name == 'workflow_dispatch' && format('Dispatch : Run CI with JDK {0} ({1})', inputs.INT_TEST_JAVA_RUNTIME_VERSION, inputs.INT_TEST_JAVA_RUNTIME_VENDOR) || '' }}"

on:
  # When triggered by a pull request, basic integration tests will run in addition to the tests related
  # to the file changes. JDK 8 (Temurin) will be used at runtime.
  pull_request:

  # When triggered by a dispatch, selected tests will run with the given integration tests JDK runtime.
  workflow_dispatch:
    inputs:
      ALL:
        description: Run all integration tests
        type: boolean
        default: true
      BASIC:
        description: Run basic integration tests
        type: boolean
        default: false
      BLOB_STORAGE:
        description: Run Blob strorage integration tests
        type: boolean
        default: false
      CASSANDRA:
        description: Run Cassandra integration tests
        type: boolean
        default: false
      COSMOS:
        description: Run Cosmos DB integration tests
        type: boolean
        default: false
      DYNAMO:
        description: Run DynamoDB integration tests
        type: boolean
        default: false
      JDBC:
        description: Run JDBC integration tests
        type: boolean
        default: false
      MULTI-STORAGE:
        description: Run multi-storage integration tests
        type: boolean
        default: false
      INT_TEST_JAVA_RUNTIME_VERSION:
        description: JDK version used to run the integration test
        type: choice
        default: '8'
        options:
          - '8'
          - '11'
          - '17'
          - '21'
      INT_TEST_JAVA_RUNTIME_VENDOR:
        description: Vendor of the JDK used to run the integration test
        type: choice
        default: 'temurin'
        options:
          - 'corretto'
          - 'microsoft'
          - 'oracle'
          - 'temurin'

  # When triggered by another action, all tests will run with the given integration test JDK runtime.
  workflow_call:
    inputs:
      ALL:
        description: Run all integration tests
        type: boolean
        default: true
      INT_TEST_JAVA_RUNTIME_VERSION:
        description: JDK version used to run the integration test
        type: string
        required: true
      INT_TEST_JAVA_RUNTIME_VENDOR:
        description: Vendor of the JDK used to run the integration test
        type: string
        required: true
env:
  ARTIFACT_SUFFIX: "${{ inputs.INT_TEST_JAVA_RUNTIME_VERSION || '8' }}_${{ inputs.INT_TEST_JAVA_RUNTIME_VENDOR || 'temurin' }}"

jobs:
  check:
    name: Gradle check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Execute Gradle 'check' task
        run: ./gradlew check buildSrc:check

      - name: Save Gradle test reports
        if: always()
        run: |
          mkdir -p /tmp/gradle_test_reports/core
          mkdir -p /tmp/gradle_test_reports/schema-loader
          mkdir -p /tmp/gradle_test_reports/data-loader/core
          mkdir -p /tmp/gradle_test_reports/data-loader/cli
          cp -a core/build/reports/tests/test /tmp/gradle_test_reports/core/
          cp -a schema-loader/build/reports/tests/test /tmp/gradle_test_reports/schema-loader/
          cp -a data-loader/core/build/reports/tests/test /tmp/gradle_test_reports/data-loader/core/
          cp -a data-loader/cli/build/reports/tests/test /tmp/gradle_test_reports/data-loader/cli/

      - name: Upload Gradle test reports
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: gradle_check_reports
          path: /tmp/gradle_test_reports

      - name: Save SpotBugs reports
        if: always()
        run: |
          mkdir -p /tmp/gradle_spotbugs_reports/core
          mkdir -p /tmp/gradle_spotbugs_reports/schema-loader
          mkdir -p /tmp/gradle_spotbugs_reports/integration-test
          mkdir -p /tmp/gradle_spotbugs_reports/data-loader/core
          mkdir -p /tmp/gradle_spotbugs_reports/data-loader/cli
          cp -a core/build/reports/spotbugs /tmp/gradle_spotbugs_reports/core/
          cp -a schema-loader/build/reports/spotbugs /tmp/gradle_spotbugs_reports/schema-loader/
          cp -a integration-test/build/reports/spotbugs /tmp/gradle_spotbugs_reports/integration-test/
          cp -a data-loader/core/build/reports/spotbugs /tmp/gradle_spotbugs_reports/data-loader/core/
          cp -a data-loader/cli/build/reports/spotbugs /tmp/gradle_spotbugs_reports/data-loader/cli/

      - name: Upload Spotbugs reports
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: gradle_spotbugs_reports
          path: /tmp/gradle_spotbugs_reports_${{ env.ARTIFACT_SUFFIX }}

  dockerfile-lint:
    name: Lint dockerfiles
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Dockerfile Lint for ScalarDB Schema Loader
        run: ./gradlew schema-loader:dockerfileLint

      - name: Dockerfile Lint for ScalarDB Data Loader CLI
        run: ./gradlew data-loader:cli:dockerfileLint

  integration-test:
    uses: ./.github/workflows/integration-test.yaml
    with:
      TRIGGERED_BY_WF_DISPATCH: ${{ github.event_name == 'workflow_dispatch' }}
      ALL: ${{ inputs.ALL || false }}
      BASIC: ${{ inputs.BASIC || false }}
      BLOB_STORAGE: ${{ inputs.BLOB_STORAGE || false }}
      CASSANDRA: ${{ inputs.CASSANDRA || false }}
      COSMOS: ${{ inputs.COSMOS || false }}
      DYNAMO: ${{ inputs.DYNAMO || false }}
      JDBC: ${{ inputs.JDBC || false }}
      MULTI-STORAGE: ${{ inputs.MULTI-STORAGE || false }}
      INT_TEST_JAVA_RUNTIME_VERSION: ${{ inputs.INT_TEST_JAVA_RUNTIME_VERSION || '8' }}
      INT_TEST_JAVA_RUNTIME_VENDOR: ${{ inputs.INT_TEST_JAVA_RUNTIME_VENDOR || 'temurin' }}
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
      OCR_USERNAME: ${{ secrets.OCR_USERNAME }}
      OCR_TOKEN: ${{ secrets.OCR_TOKEN }}

  merge-artifacts:
    if: always()
    name: Merge all artifacts
    runs-on: ubuntu-latest
    needs:
      - check
      - dockerfile-lint
      - integration-test
    steps:
      - name: Merge all artifacts
        uses: actions/upload-artifact/merge@v5
        with:
          name: ci_report_${{ env.ARTIFACT_SUFFIX }}_run_#${{ github.run_attempt }}
          pattern: "*${{ env.ARTIFACT_SUFFIX }}"
          separate-directories: true
          delete-merged: true

