name: Test Permissions

on:
  workflow_dispatch:

env:
  TERM: dumb

jobs:
  integration-test-permission-dynamo:
    name: DynamoDB Permission Integration Test
    runs-on: ubuntu-latest
    env:
      DYNAMO_ACCESS_KEY: ${{ secrets.DYNAMO_ACCESS_KEY }}
      DYNAMO_SECRET_ACCESS_KEY: ${{ secrets.DYNAMO_SECRET_ACCESS_KEY }}
      DYNAMO_REGION: ap-northeast-1

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 8 (Temurin)
        uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        env:
          AWS_ACCESS_KEY_ID: ${{ env.DYNAMO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ env.DYNAMO_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.DYNAMO_REGION }}
        with:
          limit-access-to-actor: true

      - name: Upload Gradle test reports
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: dynamo_integration_test_reports
          path: core/build/reports/tests/integrationTestDynamo
