name: Release SNAPSHOT

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set version
        id: version
        run: |
          VERSION=$(./gradlew :core:properties -q | grep "version:" | awk '{print $2}')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Upload SNAPSHOT versions for scalardb, scalardb-server, scalardb-rpc, scalardb-schema-loader, and scalardb-integration-test to Maven Snapshot Repository
        if: contains(steps.version.outputs.version, '-SNAPSHOT')
        run: |
          echo "${{secrets.SIGNING_SECRET_KEY_RING}}" | base64 -d > ~/.gradle/secring.gpg
          ./gradlew publish \
          -Psigning.keyId="${{ secrets.SIGNING_KEY_ID }}" \
          -P'signing.password'="${{ secrets.SIGNING_PASSWORD }}" \
          -Psigning.secretKeyRingFile="$(echo ~/.gradle/secring.gpg)" \
          -PossrhUsername="${{ secrets.OSSRH_USERNAMAE }}" \
          -PossrhPassword="${{ secrets.OSSRH_PASSWORD }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Create SNAPSHOT containers
        if: contains(steps.version.outputs.version, '-SNAPSHOT')
        run: ./gradlew docker

      - name: Push SNAPSHOT containers
        if: contains(steps.version.outputs.version, '-SNAPSHOT')
        run: |
          docker push ghcr.io/scalar-labs/scalardb-server:${{ steps.version.outputs.version }}
          docker push ghcr.io/scalar-labs/scalardb-schema-loader:${{ steps.version.outputs.version }}
