name: Release SNAPSHOT

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set version
        id: version
        run: |
          VERSION=$(./gradlew :core:properties -q | grep "version:" | awk '{print $2}')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Upload SNAPSHOT versions for scalardb-data-loader-core to Maven Snapshot Repository
        if: contains(steps.version.outputs.version, '-SNAPSHOT')
        run: |
          echo "${{secrets.SIGNING_SECRET_KEY_RING}}" | base64 -d > ~/.gradle/secring.gpg
          ./gradlew  data-loader:core:publish \
          -Psigning.keyId="${{ secrets.SIGNING_KEY_ID }}" \
          -P'signing.password'="${{ secrets.SIGNING_PASSWORD }}" \
          -Psigning.secretKeyRingFile="$(echo ~/.gradle/secring.gpg)" \
          -PossrhUsername="${{ secrets.OSSRH_USERNAMAE }}" \
          -PossrhPassword="${{ secrets.OSSRH_PASSWORD }}"

