name: Release SNAPSHOT

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - "[0-9]+"
      - "[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Set version
        id: version
        run: |
          VERSION=$(./gradlew :core:properties -q | grep "version:" | awk '{print $2}')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Prepare SNAPSHOT versions of artifacts in staging-deploy directories
        if: contains(steps.version.outputs.version, '-SNAPSHOT')
        run: ./gradlew publish

      - name: Upload SNAPSHOT versions of artifacts to Maven Snapshot repository
        if: contains(steps.version.outputs.version, '-SNAPSHOT')
        env:
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.MAVEN_CENTRAL_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.MAVEN_CENTRAL_GPG_SECRET_KEY }}
        run: ./gradlew jreleaserDeploy -Dorg.gradle.jvmargs="-Xmx4g"

      - name: Upload JReleaser outputs
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: jreleaser-release
          path: |
            build/jreleaser/trace.log
            build/jreleaser/output.properties

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Create SNAPSHOT containers
        if: contains(steps.version.outputs.version, '-SNAPSHOT')
        run: ./gradlew docker

      - name: Push SNAPSHOT containers
        if: contains(steps.version.outputs.version, '-SNAPSHOT')
        run: |
          docker push ghcr.io/scalar-labs/scalardb-server:${{ steps.version.outputs.version }}
          docker push ghcr.io/scalar-labs/scalardb-schema-loader:${{ steps.version.outputs.version }}
